# Generated by Django 4.2.11 on 2025-12-03 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obras', '0004_add_empresa_and_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ['empresa', 'codigo'], 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
        migrations.AlterModelOptions(
            name='userempresa',
            options={'ordering': ['empresa', 'usuario'], 'verbose_name': 'Vínculo Usuário-Empresa', 'verbose_name_plural': 'Vínculos Usuário-Empresa'},
        ),
        migrations.AlterModelOptions(
            name='workorderpermission',
            options={'ordering': ['obra', 'usuario'], 'verbose_name': 'Permissão de Obra', 'verbose_name_plural': 'Permissões de Obra'},
        ),
        migrations.RemoveIndex(
            model_name='empresa',
            name='obras_empre_codigo_idx',
        ),
        migrations.RemoveIndex(
            model_name='empresa',
            name='obras_empre_nome_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorderpermission',
            name='obras_worko_obra_id_usuari_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorderpermission',
            name='obras_worko_tipo_pe_ativ_idx',
        ),
        migrations.AddField(
            model_name='workorderpermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se a empresa está ativa', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail principal da empresa', max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(blank=True, help_text='Razão social da empresa (opcional)', max_length=200, null=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='responsavel',
            field=models.ForeignKey(help_text='Usuário responsável por gerenciar esta empresa', limit_choices_to={'groups__name': 'Responsavel Empresa'}, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone de contato', max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='userempresa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='userempresa',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa à qual o usuário está vinculado', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='obras.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='userempresa',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário vinculado à empresa', on_delete=django.db.models.deletion.CASCADE, related_name='empresas_vinculadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='workorderpermission',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se a permissão está ativa', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='workorderpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='workorderpermission',
            name='obra',
            field=models.ForeignKey(help_text='Obra à qual esta permissão se refere', on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='obras.obra', verbose_name='Obra'),
        ),
        migrations.AlterField(
            model_name='workorderpermission',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário que terá a permissão', on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_obra', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='obra',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='workorderpermission',
            index=models.Index(fields=['obra', 'tipo_permissao', 'ativo'], name='obras_worko_obra_id_9800ac_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderpermission',
            index=models.Index(fields=['usuario', 'tipo_permissao', 'ativo'], name='obras_worko_usuario_f6102c_idx'),
        ),
        # NOTA: Campos engenheiros e gestores já foram removidos na migração 0004
        # ou nunca existiram se o banco foi recriado do zero
    ]
