# Generated by Django 4.2.11 on 2025-12-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0002_delete_registroeventosuprimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(blank=True, help_text='Categoria/Classificação do insumo', max_length=100),
        ),
        migrations.AddField(
            model_name='insumo',
            name='data_atualizacao_preco',
            field=models.DateField(blank=True, help_text='Data da última atualização de preço', null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='especificacao_tecnica',
            field=models.TextField(blank=True, help_text='Especificações técnicas'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fornecedor_padrao',
            field=models.CharField(blank=True, help_text='Fornecedor padrão', max_length=255),
        ),
        migrations.AddField(
            model_name='insumo',
            name='moeda',
            field=models.CharField(default='BRL', help_text='Moeda do preço (BRL, USD, etc)', max_length=3),
        ),
        migrations.AddField(
            model_name='insumo',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações gerais sobre o insumo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço unitário de referência', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo_insumo',
            field=models.CharField(blank=True, help_text='Tipo (Material, Serviço, Equipamento, etc)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['categoria'], name='suprimentos_categor_3f2753_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['tipo_insumo'], name='suprimentos_tipo_in_91e45a_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['ativo'], name='suprimentos_ativo_765401_idx'),
        ),
    ]
