# Generated by Django 4.2.11 on 2025-12-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0004_alocacaorecebimento_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='insumo',
            name='suprimentos_categor_3f2753_idx',
        ),
        migrations.RemoveIndex(
            model_name='insumo',
            name='suprimentos_tipo_in_91e45a_idx',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='data_atualizacao_preco',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='especificacao_tecnica',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fornecedor_padrao',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='moeda',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='tipo_insumo',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='codigo_sienge',
            field=models.CharField(db_index=True, help_text='Código único do insumo no Sienge (ex: 5926)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='descricao',
            field=models.CharField(help_text='Descrição do insumo (vem do Sienge)', max_length=500),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações internas'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidade',
            field=models.CharField(default='UND', help_text='Unidade de medida (KG, M², UND, etc)', max_length=20),
        ),
    ]
