# Generated by Django 4.2.11 on 2025-12-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0005_remove_insumo_suprimentos_categor_3f2753_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmapa',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, default='A CLASSIFICAR', help_text="Categoria de aplicação (ex: FUNDAÇÃO, ESTRUTURA). Itens do Sienge entram como 'A CLASSIFICAR'.", max_length=100),
        ),
    ]
