# Generated by Django 4.2.11 on 2025-12-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0009_clear_nao_aplica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoalteracao',
            name='tipo',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('ALOCACAO', 'Alocação'), ('STATUS', 'Mudança de Status'), ('IMPORTACAO', 'Importação Sienge'), ('EXCLUSAO', 'Exclusão')], max_length=20),
        ),
    ]
