# Generated by Django 4.2.11 on 2025-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0011_alter_recebimentoobra_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='eh_macroelemento',
            field=models.BooleanField(default=True, help_text='Marcar se é um macroelemento (grande volume/valor). Insumos pequenos e cimentos geralmente NÃO são macroelementos.'),
        ),
        # Data migration: identificar automaticamente insumos existentes
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('suprimentos', 'Insumo').objects.all().update(
                eh_macroelemento=True  # Por padrão True, será ajustado quando necessário
            ),
            reverse_code=migrations.RunPython.noop
        ),
    ]
