# Generated by Django 5.2.11 on 2026-02-12 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_obras', '0001_initial'),
        ('suprimentos', '0013_remove_unidade_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alocacaorecebimento',
            index=models.Index(fields=['recebimento', 'item_mapa'], name='suprimentos_recebim_807017_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacaorecebimento',
            index=models.Index(fields=['obra', 'insumo', 'local_aplicacao'], name='suprimentos_obra_id_29cca6_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmapa',
            index=models.Index(fields=['obra', 'local_aplicacao'], name='suprimentos_obra_id_120cc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='alocacaorecebimento',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_alocada__gt', 0)), name='alocacao_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemmapa',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_planejada__gte', 0)), name='itemmapa_quantidade_planejada_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='itemmapa',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_recebida__gte', 0)), name='itemmapa_quantidade_recebida_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='recebimentoobra',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_solicitada__gte', 0)), name='recebimento_qtd_solicitada_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='recebimentoobra',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_recebida__gte', 0)), name='recebimento_qtd_recebida_nao_negativa'),
        ),
    ]
