# Generated by Django 5.2.11 on 2026-04-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_obras', '0002_obra_codigos_sienge_alternativos'),
        ('suprimentos', '0014_backend_improvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoSienge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('sha256_arquivo', models.CharField(db_index=True, max_length=64)),
                ('insumos_criados_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(blank=True, help_text='Obra do contexto no upload; vazio se o arquivo tinha várias obras.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importacoes_sienge', to='mapa_obras.obra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_sienge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação Sienge (MAPA)',
                'verbose_name_plural': 'Importações Sienge (MAPA)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='historicoalteracao',
            name='importacao_sienge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_alteracoes', to='suprimentos.importacaosienge'),
        ),
        migrations.AddField(
            model_name='recebimentoobra',
            name='importacao',
            field=models.ForeignKey(blank=True, help_text='Última importação MAPA_CONTROLE que criou ou atualizou este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos', to='suprimentos.importacaosienge'),
        ),
    ]
