# Generated by Django 5.2.11 on 2026-04-06 22:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_obras', '0002_obra_codigos_sienge_alternativos'),
        ('suprimentos', '0015_importacao_sienge_desfazer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoMapaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('aba_origem', models.CharField(default='DADOS', max_length=120)),
                ('total_linhas_lidas', models.PositiveIntegerField(default=0)),
                ('total_linhas_importadas', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes_mapa_servico', to='mapa_obras.obra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_mapa_servico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação Mapa de Serviço',
                'verbose_name_plural': 'Importações do Mapa de Serviço',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemMapaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(blank=True, default='', max_length=120)),
                ('bloco', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('pavimento', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('apto', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('atividade', models.CharField(db_index=True, max_length=200)),
                ('grupo_servicos', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status_texto', models.CharField(blank=True, default='', max_length=100)),
                ('status_percentual', models.DecimalField(blank=True, decimal_places=3, help_text='Faixa esperada: 0.000 até 1.000 (ou vazio).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('chave_uid', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='suprimentos.importacaomapaservico')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_mapa_servico', to='mapa_obras.obra')),
            ],
            options={
                'verbose_name': 'Item do Mapa de Serviço',
                'verbose_name_plural': 'Itens do Mapa de Serviço',
                'ordering': ['setor', 'bloco', 'pavimento', 'apto', 'atividade'],
                'constraints': [models.UniqueConstraint(fields=('obra', 'chave_uid'), name='uniq_item_mapa_servico_por_obra_chave')],
            },
        ),
    ]
