# Generated by Django 5.2.11 on 2026-04-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_obras', '0002_obra_codigos_sienge_alternativos'),
        ('suprimentos', '0016_importacaomapaservico_itemmapaservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMapaServicoStatusRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(db_index=True, max_length=200)),
                ('atividade_chave', models.CharField(db_index=True, max_length=220)),
                ('status_macro', models.CharField(blank=True, default='', max_length=80)),
                ('situacao', models.TextField(blank=True, default='')),
                ('prazo_execucao', models.CharField(blank=True, default='', max_length=50)),
                ('responsabilidade', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_refs', to='suprimentos.importacaomapaservico')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_status_mapa_servico', to='mapa_obras.obra')),
            ],
            options={
                'verbose_name': 'Status de Referência do Mapa de Serviço',
                'verbose_name_plural': 'Status de Referência do Mapa de Serviço',
                'ordering': ['atividade'],
                'constraints': [models.UniqueConstraint(fields=('obra', 'atividade_chave'), name='uniq_status_ref_mapa_servico_por_obra_atividade')],
            },
        ),
    ]
