# Generated by Django 5.2.11 on 2026-03-27 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistente_lplan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantEntityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('obra', 'Obra'), ('insumo', 'Insumo'), ('usuario', 'Usuário'), ('local', 'Local')], max_length=30)),
                ('alias_text', models.CharField(max_length=160, verbose_name='Alias informado')),
                ('canonical_value', models.CharField(max_length=200, verbose_name='Valor canônico')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alias de entidade do assistente',
                'verbose_name_plural': 'Aliases de entidades do assistente',
                'ordering': ['entity_type', 'alias_text'],
            },
        ),
        migrations.CreateModel(
            name='AssistantGuidedRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_text', models.CharField(max_length=240, verbose_name='Texto gatilho')),
                ('intent', models.CharField(max_length=120, verbose_name='Intenção alvo')),
                ('entities', models.JSONField(blank=True, default=dict, verbose_name='Entidades sugeridas')),
                ('priority', models.PositiveSmallIntegerField(default=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Regra guiada do assistente',
                'verbose_name_plural': 'Regras guiadas do assistente',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantLearningFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField(verbose_name='Resposta ajudou?')),
                ('corrected_intent', models.CharField(blank=True, max_length=120, verbose_name='Intenção corrigida')),
                ('corrected_entities', models.JSONField(blank=True, default=dict, verbose_name='Entidades corrigidas')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('reviewed', 'Revisado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Feedback de aprendizado do assistente',
                'verbose_name_plural': 'Feedbacks de aprendizado do assistente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assistantentityalias',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_aliases_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantentityalias',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_aliases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantguidedrule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_rules_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantguidedrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_rules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantlearningfeedback',
            name='question_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_feedbacks', to='assistente_lplan.assistantquestionlog'),
        ),
        migrations.AddField(
            model_name='assistantlearningfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantguidedrule',
            name='source_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_rules', to='assistente_lplan.assistantlearningfeedback'),
        ),
        migrations.AddIndex(
            model_name='assistantentityalias',
            index=models.Index(fields=['entity_type', 'status'], name='assistente__entity__7171d0_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantentityalias',
            index=models.Index(fields=['alias_text', 'status'], name='assistente__alias_t_5fb152_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assistantentityalias',
            unique_together={('entity_type', 'alias_text')},
        ),
        migrations.AddIndex(
            model_name='assistantlearningfeedback',
            index=models.Index(fields=['status', '-created_at'], name='assistente__status_135478_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantlearningfeedback',
            index=models.Index(fields=['question_log', '-created_at'], name='assistente__questio_3a0d81_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantguidedrule',
            index=models.Index(fields=['status', 'priority'], name='assistente__status_82288a_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantguidedrule',
            index=models.Index(fields=['intent', 'status'], name='assistente__intent_b4d2a2_idx'),
        ),
    ]
