# Generated by Django 5.2.12 on 2026-04-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistente_lplan', '0002_assistantentityalias_assistantguidedrule_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assistantquestionlog',
            new_name='assistente__user_id_5db944_idx',
            old_name='assistente_l_user_id_42f3a8_idx',
        ),
        migrations.RenameIndex(
            model_name='assistantquestionlog',
            new_name='assistente__domain_c9e578_idx',
            old_name='assistente_l_domain_aa2f69_idx',
        ),
        migrations.RenameIndex(
            model_name='assistantquestionlog',
            new_name='assistente__intent_4a6693_idx',
            old_name='assistente_l_intent_9a2966_idx',
        ),
        migrations.RenameIndex(
            model_name='assistantresponselog',
            new_name='assistente__created_647639_idx',
            old_name='assistente_l_created_e52318_idx',
        ),
    ]
