# Generated by Django 5.2.12 on 2026-05-06 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapa_obras', '0003_obra_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaPendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=10)),
                ('responsavel_externo_nome', models.CharField(blank=True, max_length=200)),
                ('responsavel_externo_whatsapp', models.CharField(blank=True, max_length=20)),
                ('responsavel_externo_email', models.EmailField(blank=True, max_length=254)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_concluidas', to=settings.AUTH_USER_MODEL)),
                ('responsavel_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoPendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=10)),
                ('destinatario_nome', models.CharField(max_length=200)),
                ('destinatario_contato', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='trackhub.etapapendencia')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('financeiro', 'Financeiro'), ('operacional', 'Operacional'), ('documento', 'Documento'), ('tarefa', 'Tarefa'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('aguardando', 'Aguardando'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('prioridade', models.CharField(choices=[('urgente', 'Urgente'), ('alta', 'Alta'), ('normal', 'Normal'), ('baixa', 'Baixa')], default='normal', max_length=10)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('sienge', 'Sienge')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='mapa_obras.obra')),
            ],
            options={
                'verbose_name': 'Pendência',
                'verbose_name_plural': 'Pendências',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='etapapendencia',
            name='pendencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='trackhub.pendencia'),
        ),
        migrations.CreateModel(
            name='ComentarioPendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='trackhub.pendencia')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['created_at'],
            },
        ),
    ]
