# Generated by Django 5.2.12 on 2026-05-07 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etapapendencia',
            name='requer_assinatura',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AssinaturaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_data', models.TextField(blank=True)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('assinado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_trackhub', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='trackhub.etapapendencia')),
            ],
            options={
                'verbose_name': 'Assinatura de Etapa',
                'verbose_name_plural': 'Assinaturas de Etapas',
            },
        ),
    ]
