# Generated by Django 5.2.12 on 2026-05-07 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhub', '0002_etapapendencia_requer_assinatura_assinaturaetapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoPendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='trackhub/anexos/%Y/%m/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('documento', 'Documento'), ('outro', 'Outro')], default='outro', max_length=10)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_trackhub', to=settings.AUTH_USER_MODEL)),
                ('pendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='trackhub.pendencia')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['created_at'],
            },
        ),
    ]
