# Generated by Django 5.2.12 on 2026-05-07 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhub', '0003_anexopendencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopendencia',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AnexoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='trackhub/comentarios/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='trackhub.comentariopendencia')),
            ],
            options={
                'verbose_name': 'Anexo de comentário',
                'verbose_name_plural': 'Anexos de comentários',
                'ordering': ['enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='trackhub/etapas/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('documento', 'Documento'), ('outro', 'Outro')], default='outro', max_length=10)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_etapa_trackhub', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='trackhub.etapapendencia')),
            ],
            options={
                'verbose_name': 'Anexo de etapa',
                'verbose_name_plural': 'Anexos de etapas',
                'ordering': ['created_at'],
            },
        ),
    ]
