# Generated by Django 5.2.12 on 2026-05-07 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhub', '0004_anexocomentario_anexoetapa_texto_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadePendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criacao', 'Criação'), ('titulo', 'Título'), ('descricao', 'Descrição'), ('status', 'Status'), ('prioridade', 'Prioridade'), ('prazo', 'Prazo'), ('tipo', 'Tipo'), ('etapa', 'Etapa'), ('comentario', 'Comentário'), ('arquivo', 'Arquivo'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='trackhub.pendencia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_pendencia_trackhub', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade da pendência',
                'verbose_name_plural': 'Atividades da pendência',
                'ordering': ['-criado_em'],
            },
        ),
    ]
