# Generated by Django 5.2.12 on 2026-05-14 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_obras', '0003_obra_project'),
        ('trackhub', '0007_notificacaoprazotrackhub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('financeiro', 'Financeiro'), ('operacional', 'Operacional'), ('documento', 'Documento'), ('tarefa', 'Tarefa'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('prioridade', models.CharField(choices=[('urgente', 'Urgente'), ('alta', 'Alta'), ('normal', 'Normal'), ('baixa', 'Baixa')], default='normal', max_length=10)),
                ('prazo_offset_dias', models.IntegerField(blank=True, null=True)),
                ('regra', models.CharField(choices=[('none', 'Não se repete'), ('daily', 'Diariamente'), ('weekdays', 'Dias da semana'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], default='none', max_length=20)),
                ('dia_semana', models.SmallIntegerField(blank=True, help_text='0=segunda … 6=domingo (Python weekday)', null=True)),
                ('dia_mes', models.SmallIntegerField(blank=True, null=True)),
                ('mes', models.SmallIntegerField(blank=True, null=True)),
                ('etapas_snapshot', models.JSONField(default=list)),
                ('proxima_execucao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_recorrentes_criadas', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias_recorrentes', to='mapa_obras.obra')),
            ],
            options={
                'verbose_name': 'Pendência recorrente',
                'verbose_name_plural': 'Pendências recorrentes',
                'ordering': ['proxima_execucao'],
            },
        ),
    ]
