# Generated by Django 5.2.12 on 2026-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhub', '0008_pendencia_recorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendenciarecorrente',
            name='parametros_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
