# Generated by Django 5.2.12 on 2026-05-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhub', '0009_pendencia_recorrente_parametros_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencia',
            name='recorrencia_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_serie', to='trackhub.pendenciarecorrente'),
        ),
    ]
