# Generated by Django 5.2.12 on 2026-05-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhub', '0010_pendencia_recorrencia_serie_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendenciarecorrente',
            name='data_criacao_original',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendenciarecorrente',
            name='prazo_original',
            field=models.DateField(blank=True, null=True),
        ),
    ]
