# Generated by Django 5.2.12 on 2026-05-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhub', '0015_pendencia_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendencia',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Data fim'),
        ),
    ]
