# Generated by Django 5.2.12 on 2026-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhub', '0016_alter_pendencia_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciarecorrente',
            name='regra',
            field=models.CharField(choices=[('none', 'Não se repete'), ('daily', 'Diariamente'), ('weekdays', 'Dias da semana'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('yearly', 'Anual')], default='none', max_length=20),
        ),
    ]
