# Generated by Django 5.2.12 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackhub", "0017_alter_pendenciarecorrente_regra"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendencia",
            name="hora_fim",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendencia",
            name="hora_inicio",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendenciarecorrente",
            name="hora_fim_original",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendenciarecorrente",
            name="hora_inicio_original",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
