# Generated by Django 4.2.11 on 2025-12-03 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_aprovacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], help_text='Aprovação ou reprovação', max_length=20, verbose_name='Decisão')),
                ('comentario', models.TextField(blank=True, help_text='Justificativa ou observações sobre a decisão', null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Decisão')),
            ],
            options={
                'verbose_name': 'Aprovação',
                'verbose_name_plural': 'Aprovações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Arquivo anexado (PDF, imagem, documento, etc.)', upload_to='anexos/%Y/%m/%d/', verbose_name='Arquivo')),
                ('nome', models.CharField(blank=True, help_text='Nome descritivo do arquivo (opcional, será preenchido automaticamente se vazio)', max_length=200, verbose_name='Nome do Arquivo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição ou observações sobre o anexo', null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Upload')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único da obra (ex: OBRA-001)', max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(help_text='Nome ou identificador da obra', max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional da obra', null=True, verbose_name='Descrição')),
                ('email_obra', models.EmailField(blank=True, help_text='E-mail para notificações relacionadas à obra (opcional)', max_length=254, null=True, verbose_name='E-mail da Obra')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a obra está ativa', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, help_text='Status antes da mudança', max_length=20, null=True, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(help_text='Novo status', max_length=20, verbose_name='Status Novo')),
                ('observacao', models.TextField(blank=True, help_text='Observação sobre a mudança de status', null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Alteração')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='data_envio',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o pedido foi enviado para aprovação (preenchido automaticamente)', null=True, verbose_name='Data de Envio'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='nome_credor',
            field=models.CharField(blank=True, default='', help_text='Nome do fornecedor/credor relacionado ao pedido', max_length=200, verbose_name='Nome do Credor'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações ou detalhes adicionais sobre o pedido', null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='tipo_solicitacao',
            field=models.CharField(blank=True, choices=[('contrato', 'Contrato'), ('medicao', 'Medição')], default='contrato', help_text='Tipo de solicitação: Contrato ou Medição', max_length=20, verbose_name='Tipo de Solicitação'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='codigo',
            field=models.CharField(help_text='Código único do pedido (ex: OB-2024-001)', max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='criado_por',
            field=models.ForeignKey(help_text='Usuário que criou o pedido (engenheiro solicitante)', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por (Solicitante)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, help_text='Data em que o pedido foi aprovado ou reprovado', null=True, verbose_name='Data de Aprovação/Reprovação'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='local',
            field=models.CharField(blank=True, help_text='Localização adicional (opcional)', max_length=300, null=True, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='prazo_estimado',
            field=models.IntegerField(blank=True, help_text='Prazo estimado em dias (opcional)', null=True, verbose_name='Prazo Estimado (dias)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado (opcional)', max_digits=15, null=True, verbose_name='Valor Estimado'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['nome_credor'], name='obras_worko_nome_cr_35d953_idx'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='alterado_por',
            field=models.ForeignKey(help_text='Usuário que fez a alteração', on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='work_order',
            field=models.ForeignKey(help_text='Pedido de obra relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='gestao_aprovacao.workorder', verbose_name='Pedido de Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='engenheiros',
            field=models.ManyToManyField(help_text='Engenheiros vinculados a esta obra', limit_choices_to={'groups__name': 'Engenheiro'}, related_name='obras_engenheiro', to=settings.AUTH_USER_MODEL, verbose_name='Engenheiros'),
        ),
        migrations.AddField(
            model_name='obra',
            name='gestores',
            field=models.ManyToManyField(help_text='Gestores e administradores que podem aprovar pedidos desta obra', limit_choices_to={'groups__name__in': ['Gestor', 'Administrador']}, related_name='obras_gestor', to=settings.AUTH_USER_MODEL, verbose_name='Gestores/Aprovadores'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='enviado_por',
            field=models.ForeignKey(help_text='Usuário que fez o upload do arquivo', on_delete=django.db.models.deletion.PROTECT, related_name='attachments_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='work_order',
            field=models.ForeignKey(help_text='Pedido de obra relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gestao_aprovacao.workorder', verbose_name='Pedido de Obra'),
        ),
        migrations.AddField(
            model_name='approval',
            name='aprovado_por',
            field=models.ForeignKey(help_text='Usuário que tomou a decisão', on_delete=django.db.models.deletion.PROTECT, related_name='approvals_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado/Reprovado por'),
        ),
        migrations.AddField(
            model_name='approval',
            name='work_order',
            field=models.ForeignKey(help_text='Pedido de obra relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='gestao_aprovacao.workorder', verbose_name='Pedido de Obra'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='obra',
            field=models.ForeignKey(blank=True, help_text='Obra à qual este pedido pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='gestao_aprovacao.obra', verbose_name='Obra'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['obra', '-created_at'], name='obras_worko_obra_id_a68106_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workorder',
            unique_together={('obra', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['work_order', '-created_at'], name='obras_statu_work_or_abef99_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['work_order', '-created_at'], name='obras_attac_work_or_53dbb3_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['enviado_por', '-created_at'], name='obras_attac_enviado_3857ff_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['work_order', '-created_at'], name='obras_appro_work_or_bda770_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['aprovado_por', '-created_at'], name='obras_appro_aprovad_54de84_idx'),
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='titulo',
        ),
    ]
