# Generated by Django 5.2.11 on 2026-02-11 14:05

import django.db.models.deletion
import gestao_aprovacao.models
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.operations import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0016_add_tag_erro_and_tipos_solicitacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_email', models.CharField(choices=[('novo_pedido', 'Novo Pedido'), ('aprovacao', 'Aprovação'), ('reprovacao', 'Reprovação')], db_index=True, max_length=20, verbose_name='Tipo de Email')),
                ('destinatarios', models.TextField(help_text='Lista de emails destinatários (separados por vírgula)', verbose_name='Destinatários')),
                ('assunto', models.CharField(max_length=500, verbose_name='Assunto')),
                ('status', models.CharField(choices=[('enviado', 'Enviado com Sucesso'), ('falhou', 'Falhou'), ('pendente', 'Pendente')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('mensagem_erro', models.TextField(blank=True, help_text='Detalhes do erro caso o envio tenha falhado', null=True, verbose_name='Mensagem de Erro')),
                ('tentativas', models.IntegerField(default=1, help_text='Número de tentativas de envio', verbose_name='Tentativas')),
                ('enviado_em', models.DateTimeField(blank=True, help_text='Data e hora em que o email foi enviado com sucesso', null=True, verbose_name='Enviado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Log de Email',
                'verbose_name_plural': 'Logs de Email',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RenameIndex(
            model_name='approval',
            new_name='gestao_apro_work_or_41e315_idx',
            old_name='obras_appro_work_or_bda770_idx',
        ),
        migrations.RenameIndex(
            model_name='approval',
            new_name='gestao_apro_aprovad_f7e535_idx',
            old_name='obras_appro_aprovad_54de84_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='gestao_apro_work_or_68b970_idx',
            old_name='obras_attac_work_or_53dbb3_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='gestao_apro_enviado_03d873_idx',
            old_name='obras_attac_enviado_3857ff_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='gestao_apro_work_or_1e6a2c_idx',
            old_name='obras_commen_work_or_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='gestao_apro_autor_i_5aba68_idx',
            old_name='obras_commen_autor_i_idx',
        ),
        migrations.RenameIndex(
            model_name='lembrete',
            new_name='gestao_apro_work_or_721525_idx',
            old_name='obras_lembr_work_or_idx',
        ),
        migrations.RenameIndex(
            model_name='lembrete',
            new_name='gestao_apro_enviado_a3d050_idx',
            old_name='obras_lembr_enviado_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='gestao_apro_usuario_097a75_idx',
            old_name='obras_notif_usuario_idx',
        ),
        migrations.RenameIndex(
            model_name='statushistory',
            new_name='gestao_apro_work_or_d255cc_idx',
            old_name='obras_statu_work_or_abef99_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='gestao_apro_status_1f2e8e_idx',
            old_name='obras_worko_status_d8e4c7_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='gestao_apro_obra_id_117875_idx',
            old_name='obras_worko_obra_id_a68106_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='gestao_apro_criado__732ff2_idx',
            old_name='obras_worko_criado__9b095a_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='gestao_apro_nome_cr_33d828_idx',
            old_name='obras_worko_nome_cr_35d953_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderpermission',
            new_name='gestao_apro_obra_id_28b938_idx',
            old_name='gestao_aprovacao_worko_obra_id_9800ac_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderpermission',
            new_name='gestao_apro_usuario_44699d_idx',
            old_name='gestao_aprovacao_worko_usuario_f6102c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='obra',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='razao_social',
        ),
        migrations.AddField(
            model_name='workorder',
            name='marcado_para_deletar',
            field=models.BooleanField(default=False, help_text='Indica se o pedido foi marcado pelo admin para ser deletado do sistema', verbose_name='Marcado para Deletar'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='marcado_para_deletar_em',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o pedido foi marcado para exclusão', null=True, verbose_name='Marcado para Deletar Em'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='marcado_para_deletar_por',
            field=models.ForeignKey(blank=True, help_text='Admin que marcou o pedido para exclusão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_marcados_deletar', to=settings.AUTH_USER_MODEL, verbose_name='Marcado para Deletar Por'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='work_order',
            field=models.ForeignKey(help_text='Pedido de obra relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='gestao_aprovacao.workorder', verbose_name='Pedido de Obra'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='arquivo',
            field=models.FileField(help_text='Arquivo anexado (PDF, imagem, documento, etc.)', upload_to=gestao_aprovacao.models.attachment_upload_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='work_order',
            field=models.ForeignKey(help_text='Pedido de obra relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gestao_aprovacao.workorder', verbose_name='Pedido de Obra'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='work_order',
            field=models.ForeignKey(help_text='Pedido de obra relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gestao_aprovacao.workorder', verbose_name='Pedido de Obra'),
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='work_order',
            field=models.ForeignKey(help_text='Pedido relacionado ao lembrete', on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='gestao_aprovacao.workorder', verbose_name='Pedido de Obra'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(default=False, help_text='Indica se a notificação foi lida', verbose_name='Lida'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(help_text='Mensagem da notificação', verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('pedido_criado', 'Novo Pedido Criado'), ('pedido_atualizado', 'Pedido Atualizado'), ('pedido_aprovado', 'Pedido Aprovado'), ('pedido_reprovado', 'Pedido Reprovado'), ('anexo_adicionado', 'Novo Anexo Adicionado'), ('anexo_removido', 'Anexo Removido'), ('comentario_adicionado', 'Novo Comentário'), ('exclusao_solicitada', 'Exclusão Solicitada'), ('exclusao_aprovada', 'Exclusão Aprovada'), ('exclusao_rejeitada', 'Exclusão Rejeitada')], help_text='Tipo da notificação', max_length=50, verbose_name='Tipo de Notificação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(help_text='Título da notificação', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Pedido relacionado à notificação (se aplicável)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='gestao_aprovacao.workorder', verbose_name='Pedido Relacionado'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='codigo',
            field=models.CharField(help_text='Código da obra (ex: OBRA-001)', max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='work_order',
            field=models.ForeignKey(help_text='Pedido de obra relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='gestao_aprovacao.workorder', verbose_name='Pedido de Obra'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente Aprovação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('reaprovacao', 'Reaprovação'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['data_envio', '-created_at'], name='gestao_apro_data_en_10751c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'data_envio'], name='gestao_apro_status_03a8d1_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['marcado_para_deletar', 'status'], name='gestao_apro_marcado_e4105e_idx'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='gestao_aprovacao.workorder', verbose_name='Pedido'),
        ),
        # Remover campos ManyToMany de forma segura (tabelas podem não existir se já foram removidas)
        SeparateDatabaseAndState(
            database_operations=[
                # Operação no banco: remover tabelas se existirem
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS gestao_aprovacao_obra_engenheiros; DROP TABLE IF EXISTS gestao_aprovacao_obra_gestores;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                # Operação no estado: remover campos do modelo
                migrations.RemoveField(
                    model_name='obra',
                    name='engenheiros',
                ),
                migrations.RemoveField(
                    model_name='obra',
                    name='gestores',
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['-criado_em', 'status'], name='gestao_apro_criado__5046fa_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['work_order', 'tipo_email'], name='gestao_apro_work_or_991e88_idx'),
        ),
    ]
