# Generated by Django 5.2.11 on 2026-02-24 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_core_diaryco_diary_i_9f2a3b_idx_core_diaryc_diary_i_e65c0f_idx_and_more'),
        ('gestao_aprovacao', '0018_obra_project_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Projeto correspondente no Diário de Obra; se preenchido, acesso ao usuário é unificado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_gestao', to='core.project', verbose_name='Projeto (Diário de Obra)'),
        ),
    ]
