# Generated by Django 5.2.12 on 2026-04-28 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao_aprovacao', '0027_obra_sigla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Normal'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='NORMAL', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impedimentos_criados', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impedimentos', to='gestao_aprovacao.obra')),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='impedimentos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemImpedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='impedimentos/imagens/%Y/%m/%d/')),
                ('legenda', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('impedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='impedimentos.impedimento')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioImpedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_impedimento', to=settings.AUTH_USER_MODEL)),
                ('impedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='impedimentos.impedimento')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='StatusImpedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(help_text='Cor em hexadecimal, ex: #3B82F6', max_length=20)),
                ('ordem', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_impedimentos', to='gestao_aprovacao.obra')),
            ],
            options={
                'ordering': ['obra', 'ordem'],
                'unique_together': {('obra', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='impedimento',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impedimentos', to='impedimentos.statusimpedimento'),
        ),
        migrations.AddIndex(
            model_name='impedimento',
            index=models.Index(fields=['obra'], name='impedimento_obra_id_a20cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='impedimento',
            index=models.Index(fields=['status'], name='impedimento_status__84f08d_idx'),
        ),
    ]
