# Generated by Django 5.2.12 on 2026-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impedimentos', '0002_seed_status_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impedimento',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='NORMAL', max_length=10),
        ),
    ]
