# Generated by Django 5.2.12 on 2026-04-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impedimentos', '0003_alter_impedimento_prioridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoImpedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='impedimentos/arquivos/%Y/%m/%d/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('impedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='impedimentos.impedimento')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
