# Generated by Django 5.2.12 on 2026-04-29 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0027_obra_sigla'),
        ('impedimentos', '0004_arquivo_impedimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaImpedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(default='#6B7280', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_impedimento_criadas', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_impedimento', to='gestao_aprovacao.obra')),
            ],
            options={
                'verbose_name': 'Categoria de impeditivo',
                'verbose_name_plural': 'Categorias de impeditivos',
                'ordering': ['nome'],
                'unique_together': {('obra', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='impedimento',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='impedimentos', to='impedimentos.categoriaimpedimento'),
        ),
    ]
