# Generated by Django 5.2.12 on 2026-04-29 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0027_obra_sigla'),
        ('impedimentos', '0006_atividadeimpedimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='impedimento',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='impedimentos.impedimento'),
        ),
        migrations.AddIndex(
            model_name='impedimento',
            index=models.Index(fields=['parent'], name='impedimento_parent__2afb6b_idx'),
        ),
    ]
