# Generated by Django 5.2.11 on 2026-06-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impedimentos', '0010_impedimento_front'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='impedimento',
            new_name='impedimento_front_i_5c19cd_idx',
            old_name='impedimentos_impedimento_front_idx',
        ),
    ]
