# Generated by Django 4.2.11 on 2026-01-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_rq10_format'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='core_activi_project_21d356_idx',
            old_name='core_activ_project_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='core_activi_project_776bb8_idx',
            old_name='core_activ_project_status_idx',
        ),
        migrations.RenameIndex(
            model_name='constructiondiary',
            new_name='core_constr_project_15b01b_idx',
            old_name='core_const_project_date_idx',
        ),
        migrations.RenameIndex(
            model_name='constructiondiary',
            new_name='core_constr_project_7217e8_idx',
            old_name='core_const_project_status_idx',
        ),
        migrations.RenameIndex(
            model_name='constructiondiary',
            new_name='core_constr_status_ed8ae2_idx',
            old_name='core_const_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyworklog',
            new_name='core_dailyw_activit_cdefe0_idx',
            old_name='core_dailyw_activity_diary_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyworklog',
            new_name='core_dailyw_diary_i_9409b1_idx',
            old_name='core_dailyw_diary_created_idx',
        ),
        migrations.RenameIndex(
            model_name='diaryimage',
            new_name='core_diaryi_diary_i_871cc7_idx',
            old_name='core_diary_diary_approv_idx',
        ),
        migrations.RenameIndex(
            model_name='equipment',
            new_name='core_equipm_code_5a3a2d_idx',
            old_name='core_equip_code_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(help_text='Código único identificador do projeto (ex: PROJ-2024-001)', max_length=50, unique=True, verbose_name='Código do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do projeto', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(help_text='Data planejada de término do projeto', verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o projeto está ativo', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Nome oficial do projeto de construção', max_length=255, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text='Data planejada de início do projeto', verbose_name='Data de Início'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='core_projec_code_119884_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', '-created_at'], name='core_projec_is_acti_5333b7_idx'),
        ),
    ]
