# Generated by Django 4.2.11 on 2026-01-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_constructiondiary_report_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, help_text='Endereço completo da obra', max_length=500, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, help_text='Nome do cliente/contratante', max_length=255, verbose_name='Contratante'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_number',
            field=models.CharField(blank=True, help_text='Número do contrato da obra', max_length=100, verbose_name='Número do Contrato'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible',
            field=models.CharField(blank=True, help_text='Nome do responsável pela obra', max_length=255, verbose_name='Responsável'),
        ),
    ]
