# Generated by Django 4.2.11 on 2026-01-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_address_project_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructiondiary',
            name='accidents',
            field=models.TextField(blank=True, help_text='Registro de acidentes ocorridos no dia', verbose_name='Acidentes'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='dds',
            field=models.TextField(blank=True, help_text='Registro do Discurso Diário de Segurança realizado', verbose_name='DDS (Discurso Diário de Segurança)'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='imminent_risks',
            field=models.TextField(blank=True, help_text='Registro de riscos eminentes identificados no dia', verbose_name='Riscos Eminentes'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='inspections',
            field=models.TextField(blank=True, help_text='Registro de fiscalizações realizadas no dia', verbose_name='Fiscalizações'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='stoppages',
            field=models.TextField(blank=True, help_text='Registro de paralisações, interrupções ou paradas no trabalho', verbose_name='Paralisações'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='weather_afternoon_condition',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('B', 'Bom'), ('R', 'Ruim')], default='', help_text='Condição climática da tarde (Bom/Ruim)', max_length=1, verbose_name='Clima Tarde - Condição'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='weather_afternoon_workable',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('T', 'Trabalhável'), ('N', 'Não Trabalhável')], default='', help_text='Se as condições da tarde permitem trabalho', max_length=1, verbose_name='Clima Tarde - Trabalhável'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='weather_morning_condition',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('B', 'Bom'), ('R', 'Ruim')], default='', help_text='Condição climática da manhã (Bom/Ruim)', max_length=1, verbose_name='Clima Manhã - Condição'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='weather_morning_workable',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('T', 'Trabalhável'), ('N', 'Não Trabalhável')], default='', help_text='Se as condições da manhã permitem trabalho', max_length=1, verbose_name='Clima Manhã - Trabalhável'),
        ),
        migrations.AddField(
            model_name='dailyworklog',
            name='location',
            field=models.CharField(blank=True, help_text='Local onde a atividade foi realizada (ex: Bloco A, Andar 2, Sala 101)', max_length=255, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='labor',
            name='role_custom',
            field=models.CharField(blank=True, help_text='Função personalizada (usado quando categoria é "Outro")', max_length=100, verbose_name='Função Personalizada'),
        ),
        migrations.AlterField(
            model_name='constructiondiary',
            name='incidents',
            field=models.TextField(blank=True, help_text='Registro de outros incidentes ou eventos relevantes do dia', verbose_name='Outros Incidentes'),
        ),
        migrations.AlterField(
            model_name='constructiondiary',
            name='interruptions',
            field=models.TextField(blank=True, help_text='DEPRECATED: Use o campo Paralisações. Mantido para compatibilidade.', verbose_name='Interrupções/Paradas (Deprecated)'),
        ),
        migrations.AlterField(
            model_name='dailyworklog',
            name='notes',
            field=models.TextField(blank=True, help_text='Descrição detalhada do que foi feito nesta atividade', verbose_name='Notas/Descrição'),
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='caption',
            field=models.CharField(help_text='Legenda descritiva da foto (obrigatório, ex: "Bloco C, serviço tal")', max_length=500, verbose_name='Legenda'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='role',
            field=models.CharField(choices=[('EN', 'Engenheiro'), ('ME', 'Mestre'), ('SE', 'Servente'), ('PE', 'Pedreiro'), ('CA', 'Carpinteiro'), ('EL', 'Eletricista'), ('HI', 'Hidráulico'), ('AR', 'Armador'), ('OU', 'Outro')], default='OU', help_text='Categoria ou função do trabalhador', max_length=2, verbose_name='Função/Categoria'),
        ),
    ]
