# Generated by Django 5.2.11 on 2026-02-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_unique_together_diary'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='diaryoccurrence',
            new_name='core_diaryo_diary_i_9a844f_idx',
            old_name='core_diaryoc_diary_i_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='occurrencetag',
            new_name='core_occurr_is_acti_9e498e_idx',
            old_name='core_occurr_is_acti_123456_idx',
        ),
        migrations.AlterField(
            model_name='constructiondiary',
            name='status',
            field=models.CharField(choices=[('PR', 'Preenchendo'), ('RV', 'Revisar'), ('AP', 'Aprovado')], default='AP', help_text='Status do relatório (Preenchido por padrão)', max_length=2, verbose_name='Status'),
        ),
    ]
