# Generated by Django 5.2.11 on 2026-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_core_diaryoc_diary_i_123456_idx_core_diaryo_diary_i_9a844f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructiondiary',
            name='status',
            field=models.CharField(choices=[('PR', 'Preenchendo'), ('RV', 'Revisar'), ('AP', 'Aprovado')], default='PR', help_text='Status do relatório (Preenchendo por padrão)', max_length=2, verbose_name='Status'),
        ),
    ]
