# Generated by Django 5.2.11 on 2026-02-24 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_project_owner_diary_comment_sent_to_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='diarycomment',
            new_name='core_diaryc_diary_i_e65c0f_idx',
            old_name='core_diaryco_diary_i_9f2a3b_idx',
        ),
        migrations.RenameIndex(
            model_name='projectowner',
            new_name='core_projec_user_id_e74eff_idx',
            old_name='core_projec_user_id_7e2b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='projectowner',
            new_name='core_projec_project_9ff930_idx',
            old_name='core_projec_project_8a3f1e_idx',
        ),
        migrations.AlterField(
            model_name='constructiondiary',
            name='status',
            field=models.CharField(choices=[('PR', 'Preenchendo'), ('SP', 'Salvamento Parcial'), ('RV', 'Revisar'), ('AP', 'Aprovado')], default='PR', help_text='Status do relatório (Preenchendo por padrão)', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dailyworklog',
            name='work_stage',
            field=models.CharField(blank=True, choices=[('IN', 'Iniciada'), ('AN', 'Em andamento'), ('TE', 'Finalizada')], default='AN', help_text='Estágio da atividade no dia', max_length=2, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user'], name='core_projec_user_id_769323_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project'], name='core_projec_project_31314b_idx'),
        ),
    ]
