# Generated by Django 5.2.11 on 2026-03-05 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_dailyworklogequipment_through'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructiondiary',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Engenheiro de campo que criou o diário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diaries', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='constructiondiary',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Gerente que revisou o diário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_diaries', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='diarycomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='diaryeditlog',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_edits', to=settings.AUTH_USER_MODEL, verbose_name='Editado por'),
        ),
        migrations.AlterField(
            model_name='diaryoccurrence',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que registrou a ocorrência', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_occurrences', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='diarysignature',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Assinante'),
        ),
        migrations.AlterField(
            model_name='diaryview',
            name='viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_views', to=settings.AUTH_USER_MODEL, verbose_name='Visualizado por'),
        ),
    ]
