# Generated by Django 5.2.11 on 2026-03-25 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_allow_user_delete_set_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='constructiondiary',
            name='edit_request_note',
            field=models.TextField(blank=True, verbose_name='Motivo / observação do pedido'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='edit_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pedido de correção em'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='edit_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_edit_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Pedido de correção por'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='provisional_edit_granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edição provisória liberada em'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='provisional_edit_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_provisional_edits_granted', to=settings.AUTH_USER_MODEL, verbose_name='Liberação feita por'),
        ),
    ]
