# Generated by Django 5.2.11 on 2026-03-25 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_diary_provisional_edit_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryCorrectionRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(verbose_name='Pedido em')),
                ('note', models.TextField(blank=True, verbose_name='Justificativa')),
                ('granted_at', models.DateTimeField(blank=True, null=True, verbose_name='Liberação em')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Quando o utilizador guardou após a edição provisória.', null=True, verbose_name='Encerrado em')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_request_logs', to='core.constructiondiary', verbose_name='Diário')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Liberação por')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pedido por')),
            ],
            options={
                'verbose_name': 'Pedido de correção (histórico)',
                'verbose_name_plural': 'Pedidos de correção (histórico)',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['-requested_at'], name='core_diaryc_request_e042ee_idx'), models.Index(fields=['diary', '-requested_at'], name='core_diaryc_diary_i_e217ee_idx')],
            },
        ),
    ]
