# Generated by Django 5.2.11 on 2026-03-31 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_diary_correction_request_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructiondiary',
            name='status',
            field=models.CharField(choices=[('PR', 'Preenchendo'), ('SP', 'Salvamento Parcial'), ('AG', 'Aguardando aprovação do gestor'), ('RG', 'Reprovado pelo gestor'), ('RV', 'Revisar'), ('AP', 'Aprovado')], default='PR', help_text='Status do relatório (Preenchendo por padrão)', max_length=2, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='DiaryApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('AP', 'Aprovado'), ('RP', 'Reprovado')], max_length=2, verbose_name='Decisão')),
                ('comment', models.TextField(blank=True, help_text='Justificativa opcional para aprovar e obrigatória para reprovar.', verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da decisão')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_approval_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='core.constructiondiary', verbose_name='Diário')),
            ],
            options={
                'verbose_name': 'Histórico de aprovação do RDO',
                'verbose_name_plural': 'Histórico de aprovação do RDO',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['diary', '-created_at'], name='core_diarya_diary_i_ea5e6d_idx'), models.Index(fields=['decision', '-created_at'], name='core_diarya_decisio_66c2b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectDiaryApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Permite desativar temporariamente sem remover o vínculo.', verbose_name='Ativo')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Apenas para ordenação visual no painel.', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdo_approvers', to='core.project', verbose_name='Obra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdo_project_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador')),
            ],
            options={
                'verbose_name': 'Aprovador de RDO por obra',
                'verbose_name_plural': 'Aprovadores de RDO por obra',
                'ordering': ['project', 'order', 'user__first_name', 'user__username'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='core_projec_project_b70a86_idx'), models.Index(fields=['user', 'is_active'], name='core_projec_user_id_85ce7d_idx')],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
