# Generated by Django 5.2.11 on 2026-04-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_constructiondiary_status_diaryapprovalhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80, verbose_name='Categoria')),
                ('severity', models.CharField(choices=[('BL', 'Bloqueante'), ('IM', 'Importante'), ('MD', 'Médio'), ('LW', 'Baixo/Dúvida')], default='MD', max_length=2, verbose_name='Severidade')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('OP', 'Aberto'), ('IP', 'Em atendimento'), ('RS', 'Resolvido'), ('CL', 'Fechado')], default='OP', max_length=2, verbose_name='Status')),
                ('screen_path', models.CharField(blank=True, max_length=255, verbose_name='Tela de origem')),
                ('browser_info', models.CharField(blank=True, max_length=255, verbose_name='Navegador/cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='core.project', verbose_name='Obra relacionada')),
            ],
            options={
                'verbose_name': 'Chamado de suporte',
                'verbose_name_plural': 'Chamados de suporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_tickets/%Y/%m/%d/', verbose_name='Arquivo')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Nome original')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.supportticket', verbose_name='Chamado')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo de chamado',
                'verbose_name_plural': 'Anexos de chamado',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_internal_note', models.BooleanField(default=False, help_text='Visível apenas para admins/superusers.', verbose_name='Nota interna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportticket', verbose_name='Chamado')),
            ],
            options={
                'verbose_name': 'Mensagem de chamado',
                'verbose_name_plural': 'Mensagens de chamado',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-created_at'], name='core_suppor_status_b2d50c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_by', '-created_at'], name='core_suppor_created_2169a3_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', '-created_at'], name='core_suppor_assigne_0727fb_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketattachment',
            index=models.Index(fields=['ticket', '-uploaded_at'], name='core_suppor_ticket__40a3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='core_suppor_ticket__f4c593_idx'),
        ),
    ]
