# Generated by Django 5.2.11 on 2026-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_supportticket_supportticketattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da 1ª resposta'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='first_response_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo 1ª resposta'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo de resolução'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('OP', 'Novo'), ('TR', 'Triagem'), ('IP', 'Em atendimento'), ('WU', 'Aguardando usuário'), ('WD', 'Aguardando deploy'), ('RS', 'Resolvido'), ('CL', 'Fechado'), ('RO', 'Reaberto')], default='OP', max_length=2, verbose_name='Status'),
        ),
    ]
