# Generated by Django 5.2.11 on 2026-04-15 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_project_sienge_codigos_alternativos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryNonWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('kind', models.CharField(choices=[('user_excused', 'Registado pelo utilizador')], default='user_excused', max_length=32, verbose_name='Tipo')),
                ('label', models.CharField(blank=True, help_text='Ex.: Obra fechada, ponte municipal', max_length=160, verbose_name='Descrição curta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_non_working_days_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_non_working_days', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Dia sem RDO (não útil)',
                'verbose_name_plural': 'Dias sem RDO (não úteis)',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'date'], name='core_diaryn_project_fdb594_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'date'), name='uniq_diary_non_working_project_date')],
            },
        ),
    ]
