# Generated by Django 5.2.11 on 2026-04-15 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_diary_non_working_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryNoReportDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('reason', models.CharField(choices=[('FE', 'Feriado'), ('FS', 'Fim de semana'), ('SP', 'Obra sem atividade neste dia')], max_length=2, verbose_name='Motivo')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Observação (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_no_report_days', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_report_days', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Dia sem relatório (justificado)',
                'verbose_name_plural': 'Dias sem relatório (justificados)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DiaryNonWorkingDay',
        ),
        migrations.AddIndex(
            model_name='diarynoreportday',
            index=models.Index(fields=['project', '-date'], name='core_diaryn_project_e13c67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diarynoreportday',
            unique_together={('project', 'date')},
        ),
    ]
