# Generated by Django 5.2.12 on 2026-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_diary_no_report_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sigla',
            field=models.CharField(blank=True, help_text='3 letras maiúsculas que identificam a obra (ex: SRS)', max_length=3, null=True, unique=True, verbose_name='Sigla'),
        ),
    ]
