# Generated by Django 5.2.11 on 2026-05-11 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_project_sigla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectowner',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='constructiondiary',
            name='sent_to_owner_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o diário foi enviado ao cliente (início da janela de 24h para comentários)', null=True, verbose_name='Enviado ao dono em'),
        ),
        migrations.AlterField(
            model_name='projectowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Cliente (usuário)'),
        ),
    ]
