# Generated by Django 5.2.12 on 2026-05-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_projectowner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_url',
            field=models.CharField(blank=True, default='', help_text='Link direto para o item notificado (ex.: pedido, restrição, TrackHub)', max_length=500, verbose_name='URL relacionada'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('diary_pending', 'Relatório Pendente de Aprovação'), ('diary_review', 'Relatório Requer Revisão'), ('activity_delayed', 'Atividade Atrasada'), ('system', 'Notificação do Sistema'), ('rdo_pendente', 'RDO Aguardando Aprovação'), ('rdo_aprovado', 'RDO Aprovado'), ('rdo_reprovado', 'RDO Reprovado/Revisão'), ('pedido_criado', 'Novo Pedido para Aprovar'), ('pedido_aprovado', 'Pedido Aprovado'), ('pedido_reprovado', 'Pedido Reprovado'), ('pedido_comentario', 'Comentário em Pedido'), ('restricao_criada', 'Nova Restrição Atribuída'), ('restricao_status', 'Status de Restrição Alterado'), ('restricao_prazo', 'Prazo de Restrição Vencendo'), ('trackhub_etapa_concluida', 'Etapa Concluída no TrackHub'), ('trackhub_prazo', 'Prazo de Etapa TrackHub')], max_length=50, verbose_name='Tipo de Notificação'),
        ),
    ]
