# Generated by Django 5.2.12 on 2026-05-11 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_notification_types_and_related_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identifica o mesmo item em várias notificações (ex.: gestao:wo:42) para marcar como lidas em lote.', max_length=160, verbose_name='Chave do evento'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_key', 'is_read'], name='core_notifi_event_k_236c1f_idx'),
        ),
    ]
