# Generated by Django 5.2.12 on 2026-05-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_notification_pedido_reenviado_atualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('diary_pending', 'Relatório Pendente de Aprovação'), ('diary_review', 'Relatório Requer Revisão'), ('activity_delayed', 'Atividade Atrasada'), ('system', 'Notificação do Sistema'), ('rdo_pendente', 'RDO Aguardando Aprovação'), ('rdo_aprovado', 'RDO Aprovado'), ('rdo_reprovado', 'RDO Reprovado/Revisão'), ('pedido_criado', 'Novo Pedido para Aprovar'), ('pedido_reenviado', 'Pedido Reenviado para Aprovação'), ('pedido_atualizado', 'Pedido Atualizado (Pendente)'), ('pedido_aprovado', 'Pedido Aprovado'), ('pedido_reprovado', 'Pedido Reprovado'), ('pedido_comentario', 'Comentário em Pedido'), ('pedido_exclusao_solicitada', 'Exclusão de Pedido Solicitada'), ('pedido_exclusao_aprovada', 'Exclusão de Pedido Aprovada'), ('pedido_exclusao_rejeitada', 'Exclusão de Pedido Rejeitada'), ('restricao_criada', 'Nova Restrição Atribuída'), ('restricao_status', 'Status de Restrição Alterado'), ('restricao_prazo', 'Prazo de Restrição Vencendo'), ('trackhub_etapa_concluida', 'Etapa Concluída no TrackHub'), ('trackhub_prazo', 'Prazo de Etapa TrackHub')], max_length=50, verbose_name='Tipo de Notificação'),
        ),
    ]
