# Generated by Django 5.2.11 on 2026-05-27 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_tipos_comunicacao(apps, schema_editor):
    TipoComunicacao = apps.get_model('core', 'TipoComunicacao')
    from core.comunicacao_constants import TIPOS_COMUNICACAO_SEED

    for row in TIPOS_COMUNICACAO_SEED:
        TipoComunicacao.objects.update_or_create(
            codigo=row['codigo'],
            defaults=row,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0043_notification_pedido_exclusao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador estável (ex.: gestcontroll.pedido_aprovado.copia_administrativa)', max_length=120, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('modulo', models.CharField(db_index=True, max_length=60, verbose_name='Módulo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('critico', 'Crítico'), ('operacional_acao', 'Operacional — ação'), ('operacional_acompanhamento', 'Operacional — acompanhamento'), ('informativo', 'Informativo'), ('auditoria_log', 'Auditoria / log')], max_length=40, verbose_name='Categoria')),
                ('criticidade', models.CharField(choices=[('critico', 'Crítico'), ('operacional', 'Operacional'), ('informativo', 'Informativo')], max_length=20, verbose_name='Criticidade')),
                ('email_padrao', models.BooleanField(default=True, verbose_name='E-mail ativo por padrão')),
                ('interno_padrao', models.BooleanField(default=False, verbose_name='Notificação interna por padrão')),
                ('resumo_padrao', models.BooleanField(default=False, verbose_name='Resumo por padrão')),
                ('permite_usuario_desativar_email', models.BooleanField(default=False, verbose_name='Usuário pode desativar e-mail')),
                ('permite_admin_desativar_email', models.BooleanField(default=True, verbose_name='Admin pode desativar e-mail')),
                ('permite_usuario_alterar_interno', models.BooleanField(default=False, verbose_name='Usuário pode alterar notificação interna')),
                ('permite_resumo', models.BooleanField(default=False, verbose_name='Permite resumo diário/semanal')),
                ('obrigatorio', models.BooleanField(default=False, help_text='Se marcado, e-mail não pode ser bloqueado por preferência.', verbose_name='Obrigatório')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de comunicação',
                'verbose_name_plural': 'Tipos de comunicação',
                'ordering': ['modulo', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaComunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', help_text='Para destinatários que não são usuários do sistema.', max_length=254, verbose_name='E-mail (sem usuário)')),
                ('email_ativo', models.BooleanField(blank=True, null=True, verbose_name='E-mail imediato')),
                ('interno_ativo', models.BooleanField(blank=True, null=True, verbose_name='Notificação interna')),
                ('resumo_ativo', models.BooleanField(blank=True, null=True, verbose_name='Resumo')),
                ('herdar_padrao', models.BooleanField(default=True, help_text='Se marcado, usa padrão do tipo/grupo (comportamento atual).', verbose_name='Herdar padrão')),
                ('bloqueado_por_admin', models.BooleanField(default=False, verbose_name='Bloqueado por admin')),
                ('observacao', models.CharField(blank=True, default='', max_length=500, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferencias_comunicacao_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_comunicacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='core.tipocomunicacao', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Preferência de comunicação',
                'verbose_name_plural': 'Preferências de comunicação',
                'indexes': [models.Index(fields=['email'], name='core_prefer_email_984705_idx'), models.Index(fields=['tipo', 'usuario'], name='core_prefer_tipo_id_f8cd50_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('tipo', 'usuario'), name='core_prefcom_unique_tipo_usuario'), models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('tipo', 'email'), name='core_prefcom_unique_tipo_email')],
            },
        ),
        migrations.CreateModel(
            name='PadraoComunicacaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ativo', models.BooleanField(blank=True, null=True, verbose_name='E-mail')),
                ('interno_ativo', models.BooleanField(blank=True, null=True, verbose_name='Interno')),
                ('resumo_ativo', models.BooleanField(blank=True, null=True, verbose_name='Resumo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padroes_comunicacao', to='auth.group', verbose_name='Grupo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padroes_grupo', to='core.tipocomunicacao', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Padrão de comunicação por grupo',
                'verbose_name_plural': 'Padrões de comunicação por grupo',
                'unique_together': {('grupo', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='LogDecisaoComunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('tipo_codigo', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('modulo', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('interno', 'Notificação interna'), ('resumo', 'Resumo')], default='email', max_length=20)),
                ('decisao', models.CharField(choices=[('enviar', 'Enviar'), ('bloquear', 'Bloquear'), ('resumo', 'Encaminhar para resumo'), ('interno', 'Somente interno')], max_length=20)),
                ('motivo', models.CharField(max_length=120, verbose_name='Motivo')),
                ('origem_destinatario', models.CharField(blank=True, default='', help_text='Ex.: aprovador, lista_fixa, env, preferencia_usuario', max_length=120)),
                ('objeto_tipo', models.CharField(blank=True, default='', max_length=80)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=64)),
                ('contexto_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_decisao_comunicacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_decisao', to='core.tipocomunicacao', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Log de decisão de comunicação',
                'verbose_name_plural': 'Logs de decisão de comunicação',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'decisao'], name='core_logdec_created_3fec05_idx'), models.Index(fields=['modulo', '-created_at'], name='core_logdec_modulo_4bbf46_idx')],
            },
        ),
        migrations.RunPython(seed_tipos_comunicacao, migrations.RunPython.noop),
    ]
