# Generated by Django 5.2.11 on 2026-06-01 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_seed_tipos_comunicacao_complementares'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, verbose_name='Identificador')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa no RDO')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_catalog_categories', to='core.project', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Categoria de equipamento (obra)',
                'verbose_name_plural': 'Categorias de equipamento (obra)',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para ocultar equipamentos que não se aplicam a esta obra.', verbose_name='Visível no RDO')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.projectequipmentcategory', verbose_name='Categoria')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_catalog_items', to='core.project', verbose_name='Obra')),
                ('source_standard_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_copies', to='core.standardequipment', verbose_name='Origem (catálogo global)')),
            ],
            options={
                'verbose_name': 'Equipamento da obra (RDO)',
                'verbose_name_plural': 'Equipamentos da obra (RDO)',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectequipmentcategory',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='core_projectequipcat_project_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projectequipmentitem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='core_projectequipitem_category_name_uniq'),
        ),
    ]
