# Generated by Django 5.2.11 on 2026-06-01 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_project_equipment_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLaborCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, verbose_name='Identificador')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa no RDO')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_catalog_categories', to='core.project', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Categoria de mão de obra (obra)',
                'verbose_name_plural': 'Categorias de mão de obra (obra)',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLaborItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do cargo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para ocultar cargos que não se aplicam a esta obra.', verbose_name='Visível no RDO')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.projectlaborcategory', verbose_name='Categoria')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_catalog_items', to='core.project', verbose_name='Obra')),
                ('source_labor_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_copies', to='core.laborcargo', verbose_name='Origem (catálogo global)')),
            ],
            options={
                'verbose_name': 'Cargo da obra (RDO)',
                'verbose_name_plural': 'Cargos da obra (RDO)',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectlaborcategory',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='core_projectlaborcat_project_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projectlaboritem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='core_projectlaboritem_category_name_uniq'),
        ),
    ]
