# Generated by Django 5.2.12 on 2026-06-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_prefcom_conditional_unique'),
        ('core', '0050_project_labor_catalog'),
    ]

    operations = [
    ]
