# Generated by Django 5.2.11 on 2026-06-08 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_merge_20260602_0943'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='constructiondiary',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ProjectFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome amigável da frente/subobra (ex: Frente Norte, Torre A)', max_length=120, verbose_name='Nome da Frente')),
                ('code', models.CharField(blank=True, help_text='Identificador opcional da frente/subobra', max_length=40, verbose_name='Código da Frente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fronts', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Frente/Subobra',
                'verbose_name_plural': 'Frentes/Subobras',
                'ordering': ['project', 'name'],
            },
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='front',
            field=models.ForeignKey(blank=True, help_text='Frente/subobra do diário (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaries', to='core.projectfront', verbose_name='Frente/Subobra'),
        ),
        migrations.AddIndex(
            model_name='constructiondiary',
            index=models.Index(fields=['project', 'front', 'date'], name='core_constr_project_f92425_idx'),
        ),
        migrations.AddConstraint(
            model_name='constructiondiary',
            constraint=models.UniqueConstraint(fields=('project', 'front', 'date'), name='core_diary_unique_project_front_date'),
        ),
        migrations.AddConstraint(
            model_name='constructiondiary',
            constraint=models.UniqueConstraint(condition=models.Q(('front__isnull', True)), fields=('project', 'date'), name='core_diary_unique_project_date_without_front'),
        ),
        migrations.AddIndex(
            model_name='projectfront',
            index=models.Index(fields=['project', 'is_active'], name='core_projec_project_739847_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfront',
            index=models.Index(fields=['project', 'name'], name='core_projec_project_d31551_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectfront',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='core_front_unique_project_name'),
        ),
        migrations.AddConstraint(
            model_name='projectfront',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('project', 'code'), name='core_front_unique_project_code_when_filled'),
        ),
    ]
