# Generated by Django 5.2.11 on 2026-06-08 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_constructiondiary_unique_together_projectfront_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFrontMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('front', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.projectfront', verbose_name='Frente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diario_front_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo usuário–frente (Diário)',
                'verbose_name_plural': 'Vínculos usuário–frente (Diário)',
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_projec_user_id_519635_idx'), models.Index(fields=['front', 'is_active'], name='core_projec_front_i_ecba54_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'front'), name='core_front_member_unique_user_front')],
            },
        ),
    ]
