# Generated by Django 5.2.11 on 2026-06-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_projectfrontmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfront',
            name='description',
            field=models.TextField(blank=True, help_text='Resumo do escopo/objetivo desta frente (mini-obra)', verbose_name='Descrição da Frente'),
        ),
        migrations.AddField(
            model_name='projectfront',
            name='location_reference',
            field=models.CharField(blank=True, help_text='Referência física para identificar rapidamente onde fica esta frente', max_length=180, verbose_name='Localização/Referência'),
        ),
        migrations.AddField(
            model_name='projectfront',
            name='responsible_name',
            field=models.CharField(blank=True, help_text='Nome do responsável operacional por esta frente', max_length=120, verbose_name='Responsável da Frente'),
        ),
    ]
