# Generated by Django 5.2.14 on 2026-06-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_constructiondiary_geolocation_data'),
        ('core', '0056_fix_terceirizada_labor_entries'),
    ]

    operations = [
    ]
