# Generated by Django 5.2.12 on 2026-06-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_merge_20260612_1544'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='constructiondiary',
            name='core_diary_unique_project_date_without_front',
        ),
        migrations.RemoveConstraint(
            model_name='projectfront',
            name='core_front_unique_project_code_when_filled',
        ),
    ]
