# Generated by Django 5.2.12 on 2026-04-13 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestao_aprovacao', '0022_fix_statushistory_observacao_charset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título (interno)')),
                ('slug', models.SlugField(blank=True, default='', help_text='Deixe em branco para gerar automaticamente a partir do título.', max_length=255, unique=True, verbose_name='Slug')),
                ('descricao_interna', models.TextField(blank=True, help_text='Visível apenas no admin.', null=True, verbose_name='Descrição interna')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo_conteudo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEM', 'Imagem'), ('IMAGEM_LINK', 'Imagem com link'), ('FORMULARIO', 'Formulário'), ('CONFIRMACAO', 'Confirmação')], default='TEXTO', max_length=32, verbose_name='Tipo de conteúdo')),
                ('titulo_visivel', models.CharField(blank=True, default='', max_length=255, verbose_name='Título visível')),
                ('subtitulo', models.CharField(blank=True, default='', max_length=255, verbose_name='Subtítulo')),
                ('texto_principal', models.TextField(blank=True, default='', verbose_name='Texto principal')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='comunicados/', verbose_name='Imagem')),
                ('link_destino', models.URLField(blank=True, null=True, verbose_name='Link de destino')),
                ('texto_botao', models.CharField(blank=True, default='', max_length=120, verbose_name='Texto do botão')),
                ('destaque_visual', models.CharField(choices=[('PADRAO', 'Padrão'), ('INFO', 'Informação'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico'), ('SUCESSO', 'Sucesso')], default='PADRAO', max_length=32, verbose_name='Destaque visual')),
                ('icone', models.CharField(blank=True, default='', help_text='Identificador ou classe do ícone (ex.: nome de ícone da UI).', max_length=120, verbose_name='Ícone')),
                ('tipo_exibicao', models.CharField(choices=[('SEMPRE', 'Sempre (toda vez que abrir)'), ('UMA_VEZ', 'Uma vez por usuário'), ('UMA_VEZ_POR_DIA', 'Uma vez por dia'), ('ATE_CONFIRMAR', 'Até confirmar leitura'), ('ATE_RESPONDER', 'Até responder'), ('X_VEZES', 'Número máximo de exibições (por usuário)'), ('X_DIAS', 'Por dias (duração)')], default='SEMPRE', max_length=32, verbose_name='Tipo de exibição')),
                ('max_exibicoes_por_usuario', models.PositiveIntegerField(blank=True, help_text='Usado quando o tipo é “Número máximo de exibições”.', null=True, verbose_name='Máx. exibições por usuário')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de fim')),
                ('dias_ativo', models.PositiveIntegerField(blank=True, help_text='Usado quando o tipo é “Por dias (duração)”.', null=True, verbose_name='Dias ativo')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='NORMAL', max_length=16, verbose_name='Prioridade')),
                ('publico_todos', models.BooleanField(default=True, verbose_name='Público: todos')),
                ('pode_fechar', models.BooleanField(default=True, verbose_name='Pode fechar')),
                ('exige_confirmacao', models.BooleanField(default=False, verbose_name='Exige confirmação de leitura')),
                ('exige_resposta', models.BooleanField(default=False, verbose_name='Exige resposta')),
                ('bloquear_ate_acao', models.BooleanField(default=False, help_text='Ex.: impedir uso do sistema até confirmar/responder.', verbose_name='Bloquear até ação')),
                ('abrir_automaticamente', models.BooleanField(default=True, verbose_name='Abrir automaticamente')),
                ('mostrar_apos_fechar', models.BooleanField(default=False, verbose_name='Mostrar após fechar')),
                ('permitir_nao_mostrar_novamente', models.BooleanField(default=False, verbose_name='Permitir “não mostrar novamente”')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('grupos_excluidos', models.ManyToManyField(blank=True, related_name='comunicados_grupos_excluidos', to='auth.group', verbose_name='Grupos excluídos')),
                ('grupos_permitidos', models.ManyToManyField(blank=True, related_name='comunicados_grupos_permitidos', to='auth.group', verbose_name='Grupos permitidos')),
                ('obras_permitidas', models.ManyToManyField(blank=True, related_name='comunicados_obras', to='gestao_aprovacao.obra', verbose_name='Obras permitidas')),
                ('usuarios_excluidos', models.ManyToManyField(blank=True, related_name='comunicados_usuarios_excluidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuários excluídos')),
                ('usuarios_permitidos', models.ManyToManyField(blank=True, related_name='comunicados_usuarios_permitidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuários permitidos')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-prioridade', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ComunicadoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da resposta')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='comunicados.comunicado', verbose_name='Comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicado_respostas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resposta ao comunicado',
                'verbose_name_plural': 'Respostas aos comunicados',
                'ordering': ['-data_resposta'],
            },
        ),
        migrations.CreateModel(
            name='ComunicadoVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeira_visualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Primeira visualização')),
                ('ultima_visualizacao', models.DateTimeField(auto_now=True, verbose_name='Última visualização')),
                ('total_visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Total de visualizações (usuário)')),
                ('fechou', models.BooleanField(default=False, verbose_name='Fechou')),
                ('confirmou_leitura', models.BooleanField(default=False, verbose_name='Confirmou leitura')),
                ('respondeu', models.BooleanField(default=False, verbose_name='Respondeu')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da resposta')),
                ('status_final', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VISUALIZADO', 'Visualizado'), ('CONFIRMADO', 'Confirmado'), ('RESPONDIDO', 'Respondido'), ('IGNORADO', 'Ignorado')], default='PENDENTE', max_length=16, verbose_name='Status final')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='comunicados.comunicado', verbose_name='Comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicado_visualizacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Visualização de comunicado',
                'verbose_name_plural': 'Visualizações de comunicados',
                'ordering': ['-ultima_visualizacao'],
                'unique_together': {('comunicado', 'usuario')},
            },
        ),
    ]
