# Generated by Django 5.2.12 on 2026-04-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='icone',
        ),
    ]
