# Generated by Django 5.2.13 on 2026-04-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0002_remove_comunicado_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='bloquear_ate_acao',
            field=models.BooleanField(default=False, help_text='Só aplica a conteúdos “Confirmação” ou “Formulário”: impede fechar até confirmar ou enviar resposta. Em texto/imagem puro não há ação obrigatória; use “Pode fechar” para bloquear o fecho de vez.', verbose_name='Bloquear até ação'),
        ),
    ]
