# Generated by Django 5.2.11 on 2026-04-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0002_remove_comunicado_icone'),
        ('gestao_aprovacao', '0022_fix_statushistory_observacao_charset'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='obras_excluidas',
            field=models.ManyToManyField(blank=True, help_text='Usuários vinculados a estes projetos (membro da obra) deixam de ver o comunicado. Só obras com projeto do Diário associado têm efeito.', related_name='comunicados_obras_excluidas', to='gestao_aprovacao.obra', verbose_name='Obras excluídas'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='publico_escopo_criterios',
            field=models.CharField(choices=[('QUALQUER', 'Qualquer critério (OU)'), ('TODOS', 'Todos os critérios (E)')], default='QUALQUER', help_text='Com público restrito: OU = basta grupo, usuário ou obra; E = tem de cumprir todos os tipos que estiverem preenchidos (ex.: grupo e obra).', max_length=16, verbose_name='Combinação dos critérios'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='publico_restrito_perfil',
            field=models.CharField(choices=[('NENHUMA', 'Sem restrição de perfil'), ('APENAS_STAFF', 'Apenas staff'), ('APENAS_SUPERUSER', 'Apenas superusuários')], default='NENHUMA', help_text='Aplicado depois do público e das exclusões; útil para avisos só à equipa interna.', max_length=20, verbose_name='Restrição de perfil'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='bloquear_ate_acao',
            field=models.BooleanField(default=False, help_text='Só aplica a conteúdos “Confirmação” ou “Formulário”: impede fechar até confirmar ou enviar resposta. Em texto/imagem puro não há ação obrigatória; use “Pode fechar” para bloquear o fecho de vez.', verbose_name='Bloquear até ação'),
        ),
    ]
