# Generated by Django 5.2.13 on 2026-04-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0003_alter_comunicado_bloquear_ate_acao'),
        ('comunicados', '0003_publico_escopo_obras_excluidas'),
    ]

    operations = [
    ]
