# Generated by Django 5.2.12 on 2026-04-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0006_comunicado_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='descricao_interna',
            field=models.TextField(blank=True, help_text='Visível apenas no admin. Máximo de 2000 caracteres.', max_length=2000, null=True, verbose_name='Descrição interna'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='exige_resposta',
            field=models.BooleanField(default=False, help_text='Em Formulário ou Confirmação: exige preencher/enviar a resposta ou marcar ciência antes de confirmar. Não combina com “Pode fechar” nem com “Permitir não mostrar novamente”.', verbose_name='Resposta obrigatória'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='link_destino',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Link de destino'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='texto_principal',
            field=models.TextField(blank=True, default='', max_length=20000, verbose_name='Texto principal'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='tipo_exibicao',
            field=models.CharField(choices=[('SEMPRE', 'Sempre (a cada novo login)'), ('UMA_VEZ', 'Uma vez por usuário'), ('UMA_VEZ_POR_DIA', 'Uma vez por dia'), ('ATE_CONFIRMAR', 'Até confirmar leitura'), ('ATE_RESPONDER', 'Até responder'), ('X_VEZES', 'Número máximo de exibições (por usuário)'), ('X_DIAS', 'Por dias (duração)')], default='SEMPRE', max_length=32, verbose_name='Tipo de exibição'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título (interno)'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='titulo_visivel',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Título visível'),
        ),
    ]
