# Generated by Django 5.2.12 on 2026-04-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0007_limites_texto_e_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='descricao_interna',
            field=models.TextField(blank=True, help_text='Visível apenas no admin. Máximo de 1000 caracteres.', max_length=1000, null=True, verbose_name='Descrição interna'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='link_destino',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de destino'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='texto_botao',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Texto do botão'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='texto_principal',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Texto principal'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título (interno)'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='titulo_visivel',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Título visível'),
        ),
    ]
