# Generated by Django 5.2.11 on 2026-06-10 20:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('dados_bancarios', models.CharField(blank=True, max_length=200, verbose_name='Conta bancária')),
                ('pis', models.CharField(blank=True, max_length=20, verbose_name='PIS')),
                ('escolaridade', models.CharField(blank=True, max_length=120, verbose_name='Escolaridade')),
                ('tamanho_camisa', models.CharField(blank=True, max_length=10, verbose_name='Tamanho camisa')),
                ('tamanho_bota', models.CharField(blank=True, max_length=10, verbose_name='Tamanho bota')),
                ('cargo', models.CharField(max_length=120, verbose_name='Cargo')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('status', models.CharField(choices=[('em_admissao', 'Em Admissão'), ('ativo', 'Ativo'), ('desligado', 'Desligado')], default='em_admissao', max_length=20, verbose_name='Status')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de admissão')),
                ('etapa_admissao', models.PositiveSmallIntegerField(default=1, help_text='1=Requisição … 5=Ativo', verbose_name='Etapa admissão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ObraLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Obra (RH)',
                'verbose_name_plural': 'Obras (RH)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('aplica_a', models.CharField(choices=[('todos', 'Todos'), ('por_cargo', 'Por Cargo'), ('por_obra', 'Por Obra')], default='todos', max_length=20, verbose_name='Aplica-se a')),
                ('tem_validade', models.BooleanField(default=False, verbose_name='Tem validade')),
                ('dias_validade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dias de validade')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AdmissaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.PositiveSmallIntegerField(verbose_name='Etapa')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/hora')),
                ('autor', models.CharField(blank=True, max_length=120, verbose_name='Autor')),
                ('concluido', models.BooleanField(default=True, verbose_name='Concluído')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_admissao', to='recursos_humanos.colaborador')),
            ],
            options={
                'verbose_name': 'Histórico de admissão',
                'verbose_name_plural': 'Históricos de admissão',
                'ordering': ['data_hora'],
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='obras',
            field=models.ManyToManyField(blank=True, related_name='colaboradores', to='recursos_humanos.obralocal'),
        ),
        migrations.CreateModel(
            name='DocumentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('pending', 'Pendente'), ('missing', 'Faltando')], default='missing', max_length=20, verbose_name='Status')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='Observação')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='recursos_humanos.colaborador')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_colaborador', to='recursos_humanos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento do colaborador',
                'verbose_name_plural': 'Documentos dos colaboradores',
                'ordering': ['tipo__ordem', 'tipo__nome'],
                'unique_together': {('colaborador', 'tipo')},
            },
        ),
    ]
