# Generated by Django 5.2.11 on 2026-06-10 21:14

import django.db.models.deletion
import recursos_humanos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0034_workorder_front'),
        ('recursos_humanos', '0003_fix_ricardo_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='gestor_aprovador',
            field=models.CharField(blank=True, max_length=120, verbose_name='Gestor aprovador'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='motivo_admissao',
            field=models.CharField(blank=True, max_length=120, verbose_name='Motivo admissão'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='observacoes_requisicao',
            field=models.TextField(blank=True, verbose_name='Observações da requisição'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='salario',
            field=models.CharField(blank=True, max_length=40, verbose_name='Salário'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(blank=True, default='CLT', max_length=40, verbose_name='Tipo de contrato'),
        ),
        migrations.AddField(
            model_name='documentocolaborador',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=recursos_humanos.models.rh_upload_path, verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='documentocolaborador',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='obralocal',
            name='gestao_obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_rh', to='gestao_aprovacao.obra', verbose_name='Obra GestControll'),
        ),
    ]
