# Generated by Django 5.2.12 on 2026-06-11 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_colaborador_gestor_aprovador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cargo (RH)',
                'verbose_name_plural': 'Cargos (RH)',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='obras_aplicaveis',
            field=models.ManyToManyField(blank=True, help_text='Preencher apenas se aplica_a=por_obra', related_name='tipos_documento', to='recursos_humanos.obralocal', verbose_name='Obras aplicáveis'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo_rh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='recursos_humanos.cargorh', verbose_name='Cargo (RH)'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='cargos_aplicaveis',
            field=models.ManyToManyField(blank=True, help_text='Preencher apenas se aplica_a=por_cargo', related_name='tipos_documento', to='recursos_humanos.cargorh', verbose_name='Cargos aplicáveis'),
        ),
    ]
