# Generated by Django 5.2.12 on 2026-06-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0005_cargorh_tipodocumento_obras_aplicaveis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='token_portal',
            field=models.CharField(blank=True, help_text='Token para acesso ao portal do candidato', max_length=64, null=True, unique=True, verbose_name='Token do portal'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='token_portal_expira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do token'),
        ),
    ]
