# Generated by Django 5.2.12 on 2026-06-12 12:12

from django.db import migrations, models


def seed_cargos_catalogo(apps, schema_editor):
    CargoCatalogo = apps.get_model('recursos_humanos', 'CargoCatalogo')
    Colaborador = apps.get_model('recursos_humanos', 'Colaborador')
    nomes = (
        Colaborador.objects.exclude(cargo='')
        .values_list('cargo', flat=True)
        .distinct()
    )
    for nome in nomes:
        CargoCatalogo.objects.get_or_create(nome=nome)


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_colaborador_token_portal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cargo (catálogo)',
                'verbose_name_plural': 'Cargos (catálogo)',
                'ordering': ['nome'],
            },
        ),
        migrations.RunPython(seed_cargos_catalogo, migrations.RunPython.noop),
    ]
