# Generated by Django 5.2.14 on 2026-06-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0011_configuracaoalertasrh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='aplica_a',
            field=models.CharField(choices=[('todos', 'Todos os colaboradores'), ('por_cargo', 'Por Cargo específico'), ('por_obra', 'Por Obra específica')], default='todos', max_length=20, verbose_name='Aplica-se a'),
        ),
    ]
