# Generated by Django 5.2.12 on 2026-06-12 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0012_alter_tipodocumento_aplica_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSignatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(blank=True, help_text='Nome que aparece no contrato', max_length=200)),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem de assinatura (0 = primeiro)')),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_signatario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de signatário',
                'verbose_name_plural': 'Configurações de signatários',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ContratoAdmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_contrato', models.FileField(blank=True, null=True, upload_to='rh/contratos/%Y/%m/', verbose_name='Contrato gerado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente assinaturas'), ('parcial', 'Assinado parcialmente'), ('concluido', 'Assinado por todos')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_admissao', to='recursos_humanos.colaborador')),
            ],
            options={
                'verbose_name': 'Contrato de admissão',
            },
        ),
        migrations.CreateModel(
            name='ContratoSignatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('colaborador', 'Colaborador'), ('empresa', 'Representante da empresa'), ('gestor', 'Gestor')], max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado')], default='pendente', max_length=20)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, help_text='PNG base64 da assinatura')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatarios', to='recursos_humanos.contratoadmissao')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signatário do contrato',
                'ordering': ['ordem'],
            },
        ),
    ]
