# Generated by Django 5.2.12 on 2026-06-12 19:36

from django.db import migrations, models


def migrar_status_parcial(apps, schema_editor):
    ContratoAdmissao = apps.get_model('recursos_humanos', 'ContratoAdmissao')
    ContratoAdmissao.objects.filter(status='parcial').update(status='pendente')


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0013_contrato_admissao_assinatura'),
    ]

    operations = [
        migrations.RunPython(migrar_status_parcial, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contratosignatario',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='contratosignatario',
            name='user',
        ),
        migrations.AlterField(
            model_name='contratoadmissao',
            name='pdf_contrato',
            field=models.FileField(blank=True, help_text='Rascunho gerado pelo sistema ou PDF assinado vindo do ZapSign', null=True, upload_to='rh/contratos/%Y/%m/', verbose_name='PDF do contrato'),
        ),
        migrations.AlterField(
            model_name='contratoadmissao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente assinatura (ZapSign)'), ('concluido', 'Contrato assinado arquivado')], default='pendente', max_length=20),
        ),
        migrations.DeleteModel(
            name='ConfiguracaoSignatario',
        ),
        migrations.DeleteModel(
            name='ContratoSignatario',
        ),
    ]
