# Generated by Django 5.2.12 on 2026-06-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0014_simplify_contrato_zapsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocolaborador',
            name='data_emissao',
            field=models.DateField(blank=True, help_text='Data em que o documento foi emitido (usada para calcular o vencimento)', null=True, verbose_name='Data de emissão'),
        ),
    ]
