# Generated by Django 5.2.12 on 2026-06-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0016_backfill_data_emissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrazoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('experiencia', 'Período de Experiência'), ('determinado', 'Contrato Determinado'), ('estagio', 'Estágio'), ('pj', 'Pessoa Jurídica')], max_length=20)),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('renovado', 'Renovado'), ('convertido', 'Convertido para indeterminado'), ('encerrado', 'Encerrado')], default='ativo', max_length=20)),
                ('renovacao_numero', models.PositiveSmallIntegerField(default=0, help_text='0 = original, 1 = primeira renovação, etc.', verbose_name='Número da renovação')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos_contrato', to='recursos_humanos.colaborador')),
                ('prazo_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacoes', to='recursos_humanos.prazocontrato')),
            ],
            options={
                'verbose_name': 'Prazo de contrato',
                'verbose_name_plural': 'Prazos de contrato',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
