# Generated by Django 5.2.11 on 2026-06-17 17:49

from django.conf import settings
from django.db import migrations, models


def seed_papeis_fluxo(apps, schema_editor):
    PapelFluxoAdmissao = apps.get_model('recursos_humanos', 'PapelFluxoAdmissao')
    padroes = [
        {
            'codigo': 'requisicao',
            'titulo': 'Aprovação da requisição',
            'descricao': (
                'Aprova ou reprova a contratação na etapa 1. '
                'Quem for indicado como gestor na requisição também pode agir, '
                'mesmo fora desta lista.'
            ),
            'etapa': 1,
            'ordem': 1,
        },
        {
            'codigo': 'conferencia_docs',
            'titulo': 'Conferência de documentos',
            'descricao': (
                'Confere e aprova cada documento enviado pelo candidato na etapa 2. '
                'Encaminha o processo para validação final quando estiver completo.'
            ),
            'etapa': 2,
            'ordem': 2,
        },
        {
            'codigo': 'validacao_final',
            'titulo': 'Validação final',
            'descricao': (
                'Revisa o pacote documental completo na etapa 3 e libera a geração do contrato, '
                'ou devolve para correções.'
            ),
            'etapa': 3,
            'ordem': 3,
        },
        {
            'codigo': 'contrato',
            'titulo': 'Contrato e arquivamento',
            'descricao': (
                'Gera o PDF, acompanha assinatura no ZapSign e arquiva o contrato assinado na etapa 4.'
            ),
            'etapa': 4,
            'ordem': 4,
        },
    ]
    for item in padroes:
        PapelFluxoAdmissao.objects.get_or_create(
            codigo=item['codigo'],
            defaults={
                'titulo': item['titulo'],
                'descricao': item['descricao'],
                'etapa': item['etapa'],
                'ordem': item['ordem'],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0021_prazocontrato_data_fim_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PapelFluxoAdmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('requisicao', 'Aprovação da requisição'), ('conferencia_docs', 'Conferência de documentos'), ('validacao_final', 'Validação final'), ('contrato', 'Contrato e arquivamento')], max_length=30, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('etapa', models.PositiveSmallIntegerField(default=1, verbose_name='Etapa do fluxo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='papeis_fluxo_admissao', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name': 'Papel do fluxo de admissão',
                'verbose_name_plural': 'Papéis do fluxo de admissão',
                'ordering': ['ordem', 'etapa'],
            },
        ),
        migrations.RunPython(seed_papeis_fluxo, migrations.RunPython.noop),
    ]
