# Generated by Django 5.2.11 on 2026-06-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0026_portal_solicitacao_restrita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(choices=[('em_admissao', 'Em admissão'), ('ativo', 'Em exercício'), ('desligado', 'Desligado')], default='em_admissao', max_length=20, verbose_name='Status'),
        ),
    ]
