# Generated by Django 5.2.14 on 2026-06-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0032_colaborador_requisicao_aprovacao_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marco', models.PositiveSmallIntegerField(choices=[(45, '45 dias'), (90, '90 dias')], verbose_name='Marco (dias)')),
                ('data_envio', models.DateField(verbose_name='Data do envio')),
                ('prazo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to='recursos_humanos.prazocontrato')),
            ],
            options={
                'verbose_name': 'Notificação de experiência enviada',
                'verbose_name_plural': 'Notificações de experiência enviadas',
                'ordering': ['-data_envio', '-pk'],
                'unique_together': {('prazo_contrato', 'marco', 'data_envio')},
            },
        ),
    ]
