# Generated by Django 5.2.14 on 2026-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0037_alter_notificacaoenviada_tipo_alerta_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoadmissao',
            name='data_admissao_oficial',
            field=models.DateField(blank=True, help_text='Informada manualmente na etapa do contrato (ZapSign). Base para marcos D45/D90 do período de experiência CLT.', null=True, verbose_name='Data de admissão oficial'),
        ),
        migrations.AlterField(
            model_name='prazocontrato',
            name='tipo',
            field=models.CharField(choices=[('experiencia', 'Período de experiência (90 dias)'), ('determinado', 'Contrato Determinado'), ('estagio', 'Estágio'), ('pj', 'Pessoa Jurídica')], max_length=20),
        ),
    ]
