# Generated by Django 5.2.11 on 2026-07-01 14:20

from django.db import migrations, models


def fix_charset_utf8mb4(apps, schema_editor):
    """Converte a tabela do colaborador para utf8mb4 no MySQL.

    Evita o erro 1366 "Incorrect string value" ao salvar textos com caracteres
    multibyte (ex.: "→", emojis) em colunas como observacoes_requisicao.
    Em SQLite/PostgreSQL é no-op.
    """
    if schema_editor.connection.vendor != 'mysql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            'ALTER TABLE recursos_humanos_colaborador '
            'CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0038_alter_contratoadmissao_data_admissao_oficial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='indicacao',
            field=models.CharField(blank=True, help_text='Preencha com o nome de quem indicou o candidato, se houver indicação.', max_length=200, verbose_name='Indicação (quem indicou)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='pix',
            field=models.CharField(blank=True, max_length=140, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='vale_transporte_valor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Valor do vale-transporte'),
        ),
        migrations.RunPython(fix_charset_utf8mb4, noop),
    ]
