# Generated by Django 5.2.11 on 2026-07-01 14:33

from django.db import migrations, models


EMPRESAS_INICIAIS = [
    'TATUAMUNHA 01',
    'JP EMPREENDIMENTOS',
    'D&P ENGENHARIA',
    'ADAMO',
]


def seed_empresas(apps, schema_editor):
    EmpresaResponsavel = apps.get_model('recursos_humanos', 'EmpresaResponsavel')
    for nome in EMPRESAS_INICIAIS:
        EmpresaResponsavel.objects.get_or_create(nome=nome)


def unseed_empresas(apps, schema_editor):
    EmpresaResponsavel = apps.get_model('recursos_humanos', 'EmpresaResponsavel')
    EmpresaResponsavel.objects.filter(nome__in=EMPRESAS_INICIAIS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0039_colaborador_indicacao_colaborador_pix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa responsável',
                'verbose_name_plural': 'Empresas responsáveis',
                'ordering': ['nome'],
            },
        ),
        migrations.RunPython(seed_empresas, unseed_empresas),
    ]
