# Generated by Django 4.2.11 on 2026-01-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_activ_project_idx_core_activi_project_21d356_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructiondiary',
            name='report_number',
            field=models.PositiveIntegerField(blank=True, help_text='Número sequencial do relatório dentro do projeto', null=True, verbose_name='Número do Relatório'),
        ),
    ]
