# Generated by Django 4.2.11 on 2026-01-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_professional_diary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructiondiary',
            name='pluviometric_index',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Índice pluviométrico do dia em milímetros (ex: 5.30)', max_digits=6, null=True, verbose_name='Índice Pluviométrico (mm)'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='weather_night_enabled',
            field=models.BooleanField(default=False, help_text='Marque se deseja registrar condições climáticas da noite', verbose_name='Registrar Clima Noite'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='weather_night_type',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('C', 'Claro'), ('N', 'Nublado'), ('CH', 'Chuvoso')], default='', help_text='Tipo de clima na noite', max_length=2, verbose_name='Clima Noite - Tipo'),
        ),
        migrations.AddField(
            model_name='constructiondiary',
            name='weather_night_workable',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('P', 'Praticável'), ('I', 'Impraticável')], default='', help_text='Se as condições da noite permitem trabalho', max_length=1, verbose_name='Clima Noite - Praticável'),
        ),
    ]
