# Generated by Django 4.2.11 on 2026-01-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_add_weather_night_and_pluviometric'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Visualização')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.constructiondiary', verbose_name='Diário')),
                ('viewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diary_views', to=settings.AUTH_USER_MODEL, verbose_name='Visualizado por')),
            ],
            options={
                'verbose_name': 'Visualização',
                'verbose_name_plural': 'Visualizações',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['diary', '-viewed_at'], name='core_diaryv_diary_i_5be433_idx')],
                'unique_together': {('diary', 'viewed_by', 'viewed_at')},
            },
        ),
        migrations.CreateModel(
            name='DiarySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('inspection', 'Responsável pela Inspeção'), ('production', 'Responsável pela Produção'), ('reviewer', 'Revisor'), ('approver', 'Aprovador')], max_length=50, verbose_name='Tipo de Assinatura')),
                ('signature_data', models.TextField(help_text='Dados da assinatura em formato base64 (canvas)', verbose_name='Dados da Assinatura')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Assinatura')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.constructiondiary', verbose_name='Diário')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diary_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Assinante')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['diary', 'signature_type'], name='core_diarys_diary_i_db6067_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiaryEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Edição')),
                ('field_name', models.CharField(blank=True, help_text='Nome do campo que foi alterado (opcional)', max_length=255, verbose_name='Campo Alterado')),
                ('old_value', models.TextField(blank=True, help_text='Valor anterior do campo (opcional)', verbose_name='Valor Anterior')),
                ('new_value', models.TextField(blank=True, help_text='Novo valor do campo (opcional)', verbose_name='Novo Valor')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre a edição', verbose_name='Observações')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='core.constructiondiary', verbose_name='Diário')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diary_edits', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Log de Edição',
                'verbose_name_plural': 'Logs de Edição',
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['diary', '-edited_at'], name='core_diarye_diary_i_4ce67e_idx')],
            },
        ),
    ]
