# Generated by Django 4.2.11 on 2026-01-13 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_diaryview_diarysignature_diaryeditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('diary_pending', 'Relatório Pendente de Aprovação'), ('diary_review', 'Relatório Requer Revisão'), ('activity_delayed', 'Atividade Atrasada'), ('system', 'Notificação do Sistema')], max_length=50, verbose_name='Tipo de Notificação')),
                ('title', models.CharField(help_text='Título da notificação', max_length=255, verbose_name='Título')),
                ('message', models.TextField(help_text='Mensagem detalhada da notificação', verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, help_text='Indica se a notificação foi lida pelo usuário', verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('related_diary', models.ForeignKey(blank=True, help_text='Diário relacionado à notificação (se aplicável)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.constructiondiary', verbose_name='Diário Relacionado')),
                ('user', models.ForeignKey(help_text='Usuário que receberá a notificação', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at', '-is_read'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiaryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Arquivo de vídeo (MP4, AVI, MOV, etc.)', upload_to='diary_videos/%Y/%m/%d/', verbose_name='Vídeo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Miniatura do vídeo (gerada automaticamente)', null=True, upload_to='diary_videos/thumbnails/%Y/%m/%d/', verbose_name='Miniatura')),
                ('caption', models.CharField(help_text='Legenda descritiva do vídeo (obrigatório)', max_length=500, verbose_name='Legenda')),
                ('duration', models.IntegerField(blank=True, help_text='Duração do vídeo em segundos', null=True, verbose_name='Duração (segundos)')),
                ('is_approved_for_report', models.BooleanField(default=True, help_text='Se False, o vídeo não será incluído no relatório mas permanece no banco', verbose_name='Aprovado para Relatório')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('diary', models.ForeignKey(help_text='Diário de obra ao qual este vídeo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.constructiondiary', verbose_name='Diário')),
            ],
            options={
                'verbose_name': 'Vídeo do Diário',
                'verbose_name_plural': 'Vídeos do Diário',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['diary', 'is_approved_for_report'], name='core_diaryv_diary_i_124935_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiaryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Arquivo anexo (PDF, DOC, XLS, etc.)', upload_to='diary_attachments/%Y/%m/%d/', verbose_name='Arquivo')),
                ('name', models.CharField(help_text='Nome descritivo do arquivo', max_length=255, verbose_name='Nome do Arquivo')),
                ('description', models.TextField(blank=True, help_text='Descrição do conteúdo do anexo', verbose_name='Descrição')),
                ('file_type', models.CharField(blank=True, help_text='Tipo MIME do arquivo (ex: application/pdf)', max_length=50, verbose_name='Tipo de Arquivo')),
                ('file_size', models.IntegerField(blank=True, help_text='Tamanho do arquivo em bytes', null=True, verbose_name='Tamanho (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('diary', models.ForeignKey(help_text='Diário de obra ao qual este anexo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.constructiondiary', verbose_name='Diário')),
            ],
            options={
                'verbose_name': 'Anexo do Diário',
                'verbose_name_plural': 'Anexos do Diário',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['diary', '-uploaded_at'], name='core_diarya_diary_i_77242b_idx')],
            },
        ),
    ]
