# Generated by Django 5.2.11 on 2026-06-10 21:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0054_projectfront_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(blank=True, db_index=True, help_text='Chave estável para reimportação (nome + pasta + tipo)', max_length=120)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('folder', models.CharField(blank=True, max_length=500, verbose_name='Pasta / trecho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('geometry_type', models.CharField(choices=[('Point', 'Ponto'), ('LineString', 'Linha'), ('Polygon', 'Polígono')], db_index=True, max_length=20)),
                ('geometry', models.JSONField(help_text='Geometria GeoJSON (coordinates apenas, sem wrapper Feature)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Centro/representativo para pontos e busca rápida', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('kind', models.CharField(choices=[('segment', 'Trecho de rota'), ('point', 'Ponto geral'), ('obstacle', 'Obstáculo'), ('vistoria', 'Vistoria'), ('caixa', 'Caixa / infra'), ('area', 'Área'), ('other', 'Outro')], db_index=True, default='other', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('blocked', 'Bloqueado'), ('vistoria', 'Vistoria')], db_index=True, default='planned', max_length=20)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Progresso (%)')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordem ao longo da rota (linhas)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_features', to='core.activity', verbose_name='Atividade EAP')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_features', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Elemento geográfico',
                'verbose_name_plural': 'Elementos geográficos',
                'ordering': ['project', 'sort_order', 'geometry_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeoObraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude central')),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude central')),
                ('default_zoom', models.PositiveSmallIntegerField(default=10, verbose_name='Zoom padrão')),
                ('import_label', models.CharField(blank=True, help_text='Ex.: KMZ IRU TIM 01-06-26', max_length=200, verbose_name='Fonte dos dados')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_config', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Configuração geo da obra',
                'verbose_name_plural': 'Configurações geo das obras',
            },
        ),
        migrations.CreateModel(
            name='GeoProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='Data')),
                ('progress_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('blocked', 'Bloqueado'), ('vistoria', 'Vistoria')], default='planned', max_length=20)),
                ('source', models.CharField(default='manual', help_text='manual | import | diario | sync', max_length=40)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='mapa_geo.geofeature', verbose_name='Elemento')),
            ],
            options={
                'verbose_name': 'Snapshot de progresso geo',
                'verbose_name_plural': 'Snapshots de progresso geo',
                'ordering': ['-snapshot_date', 'feature_id'],
            },
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['project', 'geometry_type'], name='mapa_geo_ge_project_99066c_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['project', 'kind'], name='mapa_geo_ge_project_b05558_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['project', 'external_key'], name='mapa_geo_ge_project_aa3d1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='geofeature',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key', ''), _negated=True), fields=('project', 'external_key'), name='mapa_geo_unique_external_key_per_project'),
        ),
        migrations.AddConstraint(
            model_name='geoprogresssnapshot',
            constraint=models.UniqueConstraint(fields=('feature', 'snapshot_date'), name='mapa_geo_unique_snapshot_per_feature_date'),
        ),
    ]
