# Generated by Django 5.2.12 on 2026-06-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_geo', '0002_geofeature_diary'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='geofeature',
            name='mapa_geo_unique_external_key_per_project',
        ),
    ]
