# Generated by Django 5.2.11 on 2026-02-24 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_grupos_diario_mapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['created_at'], name='accounts_us_created_b5cd99_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_us_user_id_895cc0_idx'),
        ),
    ]
