# Generated by Django 5.2.11 on 2026-04-16 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0037_diary_no_report_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identificador estável (ex.: contrato, bm, medicao).', max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de processo',
                'verbose_name_plural': 'Categorias de processo',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalFlowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow_definitions', to='core.project')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_flow_definitions', to='workflow_aprovacao.processcategory')),
            ],
            options={
                'verbose_name': 'Definição de fluxo',
                'verbose_name_plural': 'Definições de fluxo',
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_step', 'Aguardando aprovação na alçada atual'), ('approved', 'Fluxo concluído — aprovado'), ('rejected', 'Reprovado'), ('cancelled', 'Cancelado')], db_index=True, default='awaiting_step', max_length=32)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('external_system', models.CharField(blank=True, default='sienge', help_text='Sistema externo alvo (ex.: sienge).', max_length=32)),
                ('external_entity_type', models.CharField(blank=True, max_length=80)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('sync_status', models.CharField(choices=[('not_applicable', 'Sem integração externa'), ('pending', 'Aguardando envio ao Sienge'), ('in_progress', 'Sincronização em andamento'), ('synced', 'Sincronizado com Sienge'), ('failed', 'Falha na sincronização')], db_index=True, default='not_applicable', max_length=24)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('flow_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='workflow_aprovacao.approvalflowdefinition')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_initiated', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_processes', to='core.project')),
            ],
            options={
                'verbose_name': 'Processo de aprovação',
                'verbose_name_plural': 'Processos de aprovação',
                'ordering': ['-created_at'],
                'permissions': [('configure_approval_flows', 'Pode configurar fluxos da central de aprovações'), ('act_on_approval_process', 'Pode aprovar ou reprovar processos em que atua')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalIntegrationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_outbox_entries', to='workflow_aprovacao.approvalprocess')),
            ],
            options={
                'verbose_name': 'Outbox de integração',
                'verbose_name_plural': 'Outbox de integração',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Ordem crescente (1, 2, 3, …).')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_policy', models.CharField(choices=[('single_any', 'Um aprovador basta (qualquer participante aprovador)')], default='single_any', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow_aprovacao.approvalflowdefinition')),
            ],
            options={
                'verbose_name': 'Alçada',
                'verbose_name_plural': 'Alçadas',
                'ordering': ['flow', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='approvalprocess',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow_aprovacao.approvalstep'),
        ),
        migrations.CreateModel(
            name='ApprovalHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_sequence_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('submitted', 'Iniciado'), ('approved_step', 'Aprovado na alçada'), ('rejected', 'Reprovado'), ('comment', 'Comentário'), ('cancelled', 'Cancelado'), ('sync_event', 'Evento de integração')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_history_actions', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='workflow_aprovacao.approvalprocess')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow_aprovacao.approvalstep')),
            ],
            options={
                'verbose_name': 'Histórico de aprovação',
                'verbose_name_plural': 'Históricos de aprovação',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Responsável pela etapa'), ('approver', 'Aprovador'), ('viewer', 'Somente visualização')], default='approver', max_length=20)),
                ('subject_kind', models.CharField(choices=[('user', 'Usuário'), ('django_group', 'Grupo Django')], max_length=20)),
                ('django_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_participations', to='auth.group')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='workflow_aprovacao.approvalstep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante da alçada',
                'verbose_name_plural': 'Participantes da alçada',
            },
        ),
        migrations.AddField(
            model_name='approvalprocess',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_processes', to='workflow_aprovacao.processcategory'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('flow', 'sequence'), name='workflow_unique_step_sequence_per_flow'),
        ),
        migrations.AddConstraint(
            model_name='approvalstepparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('django_group__isnull', True), ('subject_kind', 'user'), ('user__isnull', False)), models.Q(('django_group__isnull', False), ('subject_kind', 'django_group'), ('user__isnull', True)), _connector='OR'), name='workflow_participant_user_xor_group'),
        ),
        migrations.AddConstraint(
            model_name='approvalflowdefinition',
            constraint=models.UniqueConstraint(fields=('project', 'category'), name='workflow_unique_flow_per_project_category'),
        ),
    ]
