# Generated by Django 5.2.11 on 2026-04-22 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_diary_no_report_day'),
        ('workflow_aprovacao', '0002_seed_process_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalConfigBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Aguardando definição de fluxo/alçadas'), ('dismissed', 'Dispensado (não criar por agora)'), ('resolved', 'Resolvido — processo criado ou reprocessado')], db_index=True, default='pending', max_length=20)),
                ('block_reason', models.CharField(choices=[('no_flow', 'Sem fluxo ativo ou sem alçada inicial'), ('unsupported_policy', 'Política de alçada não suportada')], default='no_flow', max_length=40)),
                ('external_system', models.CharField(db_index=True, default='sienge', max_length=32)),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('external_entity_type', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('last_error_message', models.TextField(blank=True)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dismiss_note', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_config_backlog', to='workflow_aprovacao.processcategory')),
                ('linked_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_backlog_entry', to='workflow_aprovacao.approvalprocess')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_config_backlog', to='core.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_approval_backlog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendência de configuração de fluxo',
                'verbose_name_plural': 'Pendências de configuração de fluxo',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('external_system', 'external_id'), name='workflow_unique_backlog_external')],
            },
        ),
    ]
