# Generated by Django 5.2.11 on 2026-04-24 17:53

from django.db import migrations, models


def _seed_sienge_sync_state(apps, schema_editor):
    Model = apps.get_model('workflow_aprovacao', 'SiengeCentralSyncState')
    Model.objects.get_or_create(
        pk=1,
        defaults={'last_ok': False, 'last_stats': {}, 'last_error': ''},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_aprovacao', '0003_approval_config_backlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiengeCentralSyncState',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_ok', models.BooleanField(default=False)),
                ('last_stats', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sync Sienge → Central (estado)',
                'verbose_name_plural': 'Sync Sienge → Central (estado)',
            },
        ),
        migrations.RunPython(_seed_sienge_sync_state, migrations.RunPython.noop),
    ]
