# Generated by Django 5.2.11 on 2026-04-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_aprovacao', '0004_sienge_central_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalprocess',
            name='external_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot não sensível do registo externo (ex.: Sienge) para exibição e auditoria.'),
        ),
        migrations.AlterField(
            model_name='processcategory',
            name='code',
            field=models.SlugField(help_text='Identificador estável (ex.: contrato, medicao).', max_length=64, unique=True),
        ),
    ]
