# Generated by Django 5.2.11 on 2026-05-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_aprovacao', '0006_merge_bm_category_into_medicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siengecentralsyncstate',
            options={'verbose_name': 'Sync Sienge para Central (estado)', 'verbose_name_plural': 'Sync Sienge para Central (estado)'},
        ),
    ]
