# Generated by Django 5.2.11 on 2026-04-27 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapa_obras', '0003_obra_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbienteOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('mapa_controle', 'Mapa de Controle'), ('suprimentos', 'Painel de Suprimentos'), ('aprovacoes', 'Fila de Aprovações'), ('custom', 'Customizável')], default='mapa_controle', max_length=40)),
                ('descricao', models.CharField(blank=True, default='', max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambientes_operacionais_criados', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes_operacionais', to='mapa_obras.obra')),
            ],
            options={
                'verbose_name': 'Ambiente operacional',
                'verbose_name_plural': 'Ambientes operacionais',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbienteVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='painel_operacional.ambienteoperacional')),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambientes_versoes_publicadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versão de ambiente',
                'verbose_name_plural': 'Versões de ambiente',
                'ordering': ['-numero', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbienteHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criar_ambiente', 'Criar ambiente'), ('salvar_rascunho', 'Salvar rascunho'), ('publicar_versao', 'Publicar versão'), ('arquivar_versao', 'Arquivar versão')], max_length=40)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambientes_historico', to=settings.AUTH_USER_MODEL)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='painel_operacional.ambienteoperacional')),
                ('versao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_historico', to='painel_operacional.ambienteversao')),
            ],
            options={
                'verbose_name': 'Histórico de ambiente',
                'verbose_name_plural': 'Histórico de ambientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbientePermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('viewer', 'Visualizador'), ('editor', 'Editor'), ('publisher', 'Publicador'), ('admin', 'Administrador')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='painel_operacional.ambienteoperacional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambientes_permissoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de ambiente',
                'verbose_name_plural': 'Permissões de ambiente',
                'constraints': [models.UniqueConstraint(fields=('ambiente', 'usuario'), name='uniq_ambiente_permissao_usuario')],
            },
        ),
        migrations.AddConstraint(
            model_name='ambienteversao',
            constraint=models.UniqueConstraint(fields=('ambiente', 'numero'), name='uniq_ambiente_versao_numero'),
        ),
    ]
