# Generated by Django 5.2.11 on 2026-04-27 15:43

from django.db import migrations, models


def seed_semantica(apps, schema_editor):
    SemanticaIndicador = apps.get_model("painel_operacional", "SemanticaIndicador")
    defaults = [
        {
            "nome_canonico": "percentual_concluido",
            "descricao_operacional": "Percentual médio concluído no recorte do mapa.",
            "dominio": "controle",
            "origem_dado": "ItemMapaServico.status_percentual",
            "formula_regra": "media(status_percentual) no recorte",
            "granularidade": "obra,setor,bloco,pavimento,unidade,atividade",
            "limites_faixas": "0-100%",
            "caveats": "Valor depende da qualidade de preenchimento da importação.",
        },
        {
            "nome_canonico": "itens_em_andamento",
            "descricao_operacional": "Quantidade de itens em execução parcial.",
            "dominio": "controle",
            "origem_dado": "ItemMapaServico.status_percentual/status_texto",
            "formula_regra": "count(status_percentual entre 0 e 1)",
            "granularidade": "obra,setor,bloco,pavimento,unidade",
            "limites_faixas": "inteiro",
            "caveats": "Pode variar por regra de normalização textual.",
        },
        {
            "nome_canonico": "saldo_a_entregar",
            "descricao_operacional": "Saldo de material ainda não entregue no pipeline.",
            "dominio": "suprimentos",
            "origem_dado": "ItemMapa.saldo_a_entregar",
            "formula_regra": "sum(saldo_a_entregar) por recorte",
            "granularidade": "obra,categoria,insumo,local",
            "limites_faixas": ">=0",
            "caveats": "Dependente da reconciliação de SC/PC e recebimentos.",
        },
    ]
    for row in defaults:
        SemanticaIndicador.objects.get_or_create(nome_canonico=row["nome_canonico"], defaults=row)


def unseed_semantica(apps, schema_editor):
    SemanticaIndicador = apps.get_model("painel_operacional", "SemanticaIndicador")
    SemanticaIndicador.objects.filter(
        nome_canonico__in=["percentual_concluido", "itens_em_andamento", "saldo_a_entregar"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('painel_operacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_canonico', models.CharField(max_length=120, unique=True)),
                ('descricao_operacional', models.CharField(max_length=280)),
                ('dominio', models.CharField(choices=[('controle', 'Controle de obra'), ('suprimentos', 'Suprimentos'), ('aprovacao', 'Aprovação'), ('diario', 'Diário de obra')], default='controle', max_length=30)),
                ('origem_dado', models.CharField(blank=True, default='', max_length=180)),
                ('formula_regra', models.TextField(blank=True, default='')),
                ('granularidade', models.CharField(blank=True, default='', max_length=120)),
                ('limites_faixas', models.CharField(blank=True, default='', max_length=180)),
                ('caveats', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicador semântico',
                'verbose_name_plural': 'Indicadores semânticos',
                'ordering': ['dominio', 'nome_canonico'],
            },
        ),
        migrations.RunPython(seed_semantica, unseed_semantica),
    ]
