# Generated by Django 5.2.11 on 2026-04-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_operacional', '0002_semanticaindicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbienteElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_externa', models.CharField(blank=True, default='', max_length=120)),
                ('titulo', models.CharField(blank=True, default='', max_length=180)),
                ('tipo', models.CharField(choices=[('block', 'Bloco'), ('table', 'Tabela'), ('group', 'Grupo'), ('area', 'Área'), ('kpi', 'KPI')], default='block', max_length=20)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=320)),
                ('height', models.IntegerField(default=180)),
                ('z_index', models.IntegerField(default=0)),
                ('camada', models.JSONField(blank=True, default=dict)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('origem_layout', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='painel_operacional.ambienteoperacional')),
                ('versao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos', to='painel_operacional.ambienteversao')),
            ],
            options={
                'verbose_name': 'Elemento de ambiente',
                'verbose_name_plural': 'Elementos de ambiente',
                'ordering': ['z_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AmbienteCelula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha_idx', models.PositiveIntegerField(default=0)),
                ('coluna_idx', models.PositiveIntegerField(default=0)),
                ('valor', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(blank=True, default='texto', max_length=40)),
                ('estilo', models.JSONField(blank=True, default=dict)),
                ('origem', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celulas', to='painel_operacional.ambienteelemento')),
            ],
            options={
                'verbose_name': 'Célula de ambiente',
                'verbose_name_plural': 'Células de ambiente',
                'ordering': ['linha_idx', 'coluna_idx'],
            },
        ),
        migrations.AddConstraint(
            model_name='ambienteelemento',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_externa', ''), _negated=True), fields=('ambiente', 'chave_externa'), name='uniq_ambiente_elemento_chave_externa'),
        ),
        migrations.AddConstraint(
            model_name='ambientecelula',
            constraint=models.UniqueConstraint(fields=('elemento', 'linha_idx', 'coluna_idx'), name='uniq_ambiente_celula_posicao'),
        ),
    ]
