# Generated by Django 5.2.12 on 2026-05-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel_operacional', '0004_ambienteoperacional_modo_editor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ambienteelemento',
            name='uniq_ambiente_elemento_chave_externa',
        ),
    ]
