INTENT_LOCATE_SUPPLY = "localizar_insumo"
INTENT_LIST_OBRA_PENDING = "listar_pendencias_obra"
INTENT_LIST_PENDING_APPROVALS = "listar_aprovacoes_pendentes"
INTENT_RDO_BY_DATE = "consultar_rdo_por_data"
INTENT_OBRA_SUMMARY = "resumo_obra"
INTENT_USER_STATUS = "status_usuario"
INTENT_UNALLOCATED_ITEMS = "itens_sem_alocacao"
INTENT_REJECTED_REQUESTS = "solicitacoes_reprovadas"
INTENT_OBRA_BOTTLENECKS = "gargalos_obra"
INTENT_INTELIGENCIA_INTEGRADA = "inteligencia_obra_integrada"
INTENT_RELATORIO_LOCAL_MAPA = "relatorio_local_mapa"
INTENT_RELATORIO_RDO_PERIOD = "relatorio_rdo_periodo"
INTENT_FALLBACK = "fallback"

# Fase 1 — suprimentos pipeline, fila atraso, restrições
INTENT_PANORAMA_PIPELINE_SUPRIMENTOS = "panorama_pipeline_suprimentos"
INTENT_ITENS_ATRASADOS_SUPRIMENTOS = "itens_atrasados_suprimentos"
INTENT_FILA_ATRASO_APROVACOES = "fila_atraso_aprovacoes"
INTENT_CONSULTAR_RESTRICOES_OBRA = "consultar_restricoes_obra"
INTENT_RESTRICOES_CRITICAS_ESCOPO = "restricoes_criticas_escopo"

# Fase 2 — mapa controle, mapa geo, trackhub, RH resumo
INTENT_PANORAMA_MAPA_CONTROLE = "panorama_mapa_controle"
INTENT_RESUMO_MAPA_GEOGRAFICO = "resumo_mapa_geografico"
INTENT_CONSULTAR_PENDENCIAS_TRACKHUB = "consultar_pendencias_trackhub"
INTENT_PENDENCIAS_VENCIDAS_TRACKHUB = "pendencias_vencidas_trackhub"
INTENT_RESUMO_ALERTAS_RH = "resumo_alertas_rh"

# Fase 3 — gestão avançada, mapa geo detalhe, RH fluxo
INTENT_DESEMPENHO_EQUIPE_GEST = "desempenho_equipe_gest"
INTENT_LISTAR_FRENTES_OBRA = "listar_frentes_obra"
INTENT_PEDIDOS_POR_FRENTE = "pedidos_por_frente"
INTENT_ALERTAS_MAPA_GEOGRAFICO = "alertas_mapa_geografico"
INTENT_MARCADORES_GPS_RDO = "marcadores_gps_rdo"
INTENT_ADMISSOES_EM_ANDAMENTO = "admissoes_em_andamento"
INTENT_DOCUMENTOS_VENCENDO_RH = "documentos_vencendo_rh"
INTENT_PRAZOS_CONTRATO_RH = "prazos_contrato_rh"

# Fase 4 — ambientes, panoramas, detalhes
INTENT_LISTAR_AMBIENTES_OPERACIONAIS = "listar_ambientes_operacionais"
INTENT_PANORAMA_SUPRIMENTOS_GERAL = "panorama_suprimentos_geral"
INTENT_RESTRICOES_POR_RESPONSAVEL = "restricoes_por_responsavel"
INTENT_RESUMO_FILA_TRACKHUB = "resumo_fila_trackhub"

SUPPORTED_INTENTS = {
    INTENT_LOCATE_SUPPLY,
    INTENT_LIST_OBRA_PENDING,
    INTENT_LIST_PENDING_APPROVALS,
    INTENT_RDO_BY_DATE,
    INTENT_OBRA_SUMMARY,
    INTENT_USER_STATUS,
    INTENT_UNALLOCATED_ITEMS,
    INTENT_REJECTED_REQUESTS,
    INTENT_OBRA_BOTTLENECKS,
    INTENT_INTELIGENCIA_INTEGRADA,
    INTENT_RELATORIO_LOCAL_MAPA,
    INTENT_RELATORIO_RDO_PERIOD,
    INTENT_FALLBACK,
    INTENT_PANORAMA_PIPELINE_SUPRIMENTOS,
    INTENT_ITENS_ATRASADOS_SUPRIMENTOS,
    INTENT_FILA_ATRASO_APROVACOES,
    INTENT_CONSULTAR_RESTRICOES_OBRA,
    INTENT_RESTRICOES_CRITICAS_ESCOPO,
    INTENT_PANORAMA_MAPA_CONTROLE,
    INTENT_RESUMO_MAPA_GEOGRAFICO,
    INTENT_CONSULTAR_PENDENCIAS_TRACKHUB,
    INTENT_PENDENCIAS_VENCIDAS_TRACKHUB,
    INTENT_RESUMO_ALERTAS_RH,
    INTENT_DESEMPENHO_EQUIPE_GEST,
    INTENT_LISTAR_FRENTES_OBRA,
    INTENT_PEDIDOS_POR_FRENTE,
    INTENT_ALERTAS_MAPA_GEOGRAFICO,
    INTENT_MARCADORES_GPS_RDO,
    INTENT_ADMISSOES_EM_ANDAMENTO,
    INTENT_DOCUMENTOS_VENCENDO_RH,
    INTENT_PRAZOS_CONTRATO_RH,
    INTENT_LISTAR_AMBIENTES_OPERACIONAIS,
    INTENT_PANORAMA_SUPRIMENTOS_GERAL,
    INTENT_RESTRICOES_POR_RESPONSAVEL,
    INTENT_RESUMO_FILA_TRACKHUB,
}
