INTENT_LOCATE_SUPPLY = "localizar_insumo"
INTENT_LIST_OBRA_PENDING = "listar_pendencias_obra"
INTENT_LIST_PENDING_APPROVALS = "listar_aprovacoes_pendentes"
INTENT_RDO_BY_DATE = "consultar_rdo_por_data"
INTENT_OBRA_SUMMARY = "resumo_obra"
INTENT_USER_STATUS = "status_usuario"
INTENT_UNALLOCATED_ITEMS = "itens_sem_alocacao"
INTENT_REJECTED_REQUESTS = "solicitacoes_reprovadas"
INTENT_OBRA_BOTTLENECKS = "gargalos_obra"
INTENT_FALLBACK = "fallback"

SUPPORTED_INTENTS = {
    INTENT_LOCATE_SUPPLY,
    INTENT_LIST_OBRA_PENDING,
    INTENT_LIST_PENDING_APPROVALS,
    INTENT_RDO_BY_DATE,
    INTENT_OBRA_SUMMARY,
    INTENT_USER_STATUS,
    INTENT_UNALLOCATED_ITEMS,
    INTENT_REJECTED_REQUESTS,
    INTENT_OBRA_BOTTLENECKS,
    INTENT_FALLBACK,
}

