# Generated by Django 5.2.12 on 2026-06-04 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapa_obras', '0003_obra_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Formato E.164, ex.: +5581999999999', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário WhatsApp',
                'verbose_name_plural': 'Usuários WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IaPermissaoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_consultar_rdo', models.BooleanField(default=True)),
                ('pode_consultar_pedidos', models.BooleanField(default=True)),
                ('pode_receber_pdf', models.BooleanField(default=True)),
                ('obras_autorizadas', models.ManyToManyField(blank=True, help_text='Vazio = acesso a todas as obras do usuário.', to='mapa_obras.obra')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_consulta', to='whatsapp_ia.usuariowhatsapp')),
            ],
            options={
                'verbose_name': 'Permissão de consulta IA',
                'verbose_name_plural': 'Permissões de consulta IA',
            },
        ),
        migrations.CreateModel(
            name='IaMensagemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem_recebida', models.TextField()),
                ('intencao_detectada', models.CharField(blank=True, max_length=100)),
                ('funcao_chamada', models.CharField(blank=True, max_length=100)),
                ('resposta_enviada', models.TextField(blank=True)),
                ('status', models.CharField(default='ok', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_log', to='whatsapp_ia.usuariowhatsapp')),
            ],
            options={
                'verbose_name': 'Log de mensagem IA',
                'verbose_name_plural': 'Logs de mensagens IA',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IaErroLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erro', models.TextField()),
                ('payload_resumido', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_log', to='whatsapp_ia.usuariowhatsapp')),
            ],
            options={
                'verbose_name': 'Log de erro IA',
                'verbose_name_plural': 'Logs de erros IA',
                'ordering': ['-criado_em'],
            },
        ),
    ]
