# Generated by Django 5.2.11 on 2026-04-15 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('retention_days', models.PositiveIntegerField(blank=True, help_text='Dias de retenção sugeridos; None = indefinido / manual.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política de retenção (auditoria)',
                'verbose_name_plural': 'Políticas de retenção (auditoria)',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_code', models.CharField(db_index=True, max_length=80, verbose_name='Código da ação')),
                ('module', models.CharField(db_index=True, default='gestao', help_text='Ex.: gestao, accounts, core.', max_length=32, verbose_name='Módulo')),
                ('summary', models.CharField(max_length=500, verbose_name='Resumo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Detalhes (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=256, verbose_name='User-Agent')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_as_actor', to=settings.AUTH_USER_MODEL, verbose_name='Quem executou')),
                ('subject_user', models.ForeignKey(blank=True, help_text='Preenchido quando a ação incide sobre um usuário (cadastro, permissões, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_as_subject', to=settings.AUTH_USER_MODEL, verbose_name='Usuário alvo')),
            ],
            options={
                'verbose_name': 'Evento de auditoria',
                'verbose_name_plural': 'Eventos de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_user', '-created_at'], name='audit_audit_subject_3ccc25_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_fb4253_idx'), models.Index(fields=['action_code', '-created_at'], name='audit_audit_action__9cd8e1_idx'), models.Index(fields=['module', '-created_at'], name='audit_audit_module_9814af_idx')],
            },
        ),
    ]
