# Generated by Django 5.2.11 on 2026-03-17 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('ponto', 'Ponto'), ('erp', 'ERP'), ('geo', 'GEO')], db_index=True, max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('sharepoint', 'SharePoint/OneDrive')], default='sharepoint', max_length=40)),
                ('reference_type', models.CharField(db_index=True, max_length=80)),
                ('reference_id', models.PositiveIntegerField(db_index=True)),
                ('file_name', models.CharField(max_length=255)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('version_label', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_type', 'reference_id', 'provider'], name='integration_referen_9cea03_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='teams', max_length=40)),
                ('command_text', models.CharField(blank=True, max_length=500)),
                ('command_name', models.CharField(blank=True, db_index=True, max_length=80)),
                ('external_user_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('external_user_email', models.EmailField(blank=True, max_length=254)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('source', models.CharField(blank=True, db_index=True, max_length=120)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=80)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('failed', 'Falha')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status', '-created_at'], name='integration_provide_b8ce1a_idx'), models.Index(fields=['event_type', '-created_at'], name='integration_event_t_5eef5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='clicksign', max_length=40)),
                ('reference_type', models.CharField(db_index=True, max_length=80)),
                ('reference_id', models.PositiveIntegerField(db_index=True)),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_email', models.EmailField(max_length=254)),
                ('external_request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('signed', 'Assinado'), ('declined', 'Recusado'), ('expired', 'Expirado')], db_index=True, default='draft', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status', '-created_at'], name='integration_provide_ac4aee_idx')],
            },
        ),
    ]
