# Generated by Django 4.2.11 on 2025-12-03 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do pedido (ex: OB-2024-001)', max_length=50, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(help_text='Título descritivo do pedido', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do pedido de obra', null=True, verbose_name='Descrição')),
                ('cliente', models.CharField(help_text='Nome do cliente ou empresa', max_length=200, verbose_name='Cliente')),
                ('local', models.CharField(help_text='Endereço ou localização da obra', max_length=300, verbose_name='Local da Obra')),
                ('valor_estimado', models.DecimalField(decimal_places=2, help_text='Valor estimado da obra em reais', max_digits=15, verbose_name='Valor Estimado')),
                ('prazo_estimado', models.IntegerField(help_text='Prazo estimado de conclusão em dias', verbose_name='Prazo Estimado (dias)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente Aprovação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_aprovacao', models.DateTimeField(blank=True, help_text='Data em que o pedido foi aprovado ou reprovado', null=True, verbose_name='Data de Aprovação')),
                ('criado_por', models.ForeignKey(help_text='Usuário que criou o pedido', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Pedido de Obra',
                'verbose_name_plural': 'Pedidos de Obra',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='obras_worko_status_d8e4c7_idx'), models.Index(fields=['criado_por', '-created_at'], name='obras_worko_criado__9b095a_idx')],
            },
        ),
    ]
