# Generated by Django 5.2.11 on 2026-03-05 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0019_alter_obra_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que tomou a decisão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado/Reprovado por'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='enviado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez o upload do arquivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='autor',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez o comentário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_feitos', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável por gerenciar esta empresa', limit_choices_to={'groups__name': 'Responsavel Empresa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Empresa'),
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='enviado_para',
            field=models.ForeignKey(blank=True, help_text='Aprovador que recebeu o lembrete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lembretes_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Enviado Para'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='alterado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez a alteração', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o pedido (engenheiro solicitante)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por (Solicitante)'),
        ),
    ]
