# Generated by Django 5.2.11 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0020_allow_user_delete_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='tipo_email',
            field=models.CharField(
                choices=[
                    ('novo_pedido', 'Novo Pedido'),
                    ('aprovacao', 'Aprovação'),
                    ('reprovacao', 'Reprovação'),
                    ('credenciais_usuario', 'Credenciais de Usuário'),
                    ('diario_dono_obra', 'Diário para Dono da Obra'),
                    ('diario_obra', 'Diário de Obra'),
                ],
                db_index=True,
                max_length=20,
                verbose_name='Tipo de Email',
            ),
        ),
    ]
