# Generated by Django 5.2.11 on 2026-04-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0022_fix_statushistory_observacao_charset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprovacaoEmailDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Endereço que recebe notificação em pedidos aprovados (cópia).', max_length=254, unique=True, verbose_name='E-mail')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição e prioridade (menor primeiro).', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Destinatário (e-mail aprovação)',
                'verbose_name_plural': 'Destinatários (e-mail aprovação)',
                'ordering': ['ordem', 'email'],
            },
        ),
    ]
