# Generated by Django 5.2.12 on 2026-04-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0023_aprovacaoemaildestinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='valor_medicao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da medição informado pelo solicitante (controle fora do Sienge). Usar quando o tipo for Medição.', max_digits=15, null=True, verbose_name='Valor de medição (R$)'),
        ),
    ]
