# Generated by Django 5.2.11 on 2026-04-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0024_workorder_valor_medicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagerro',
            name='tipo_solicitacao',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('validacao_contrato', 'Validação de Contrato'), ('medicao', 'Medição'), ('ordem_servico', 'Ordem de Serviço (OS)'), ('mapa_cotacao', 'Mapa de Cotação')], help_text='Tipo de solicitação ao qual esta tag se aplica', max_length=20, verbose_name='Tipo de Solicitação'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tipo_solicitacao',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('validacao_contrato', 'Validação de Contrato'), ('medicao', 'Medição'), ('ordem_servico', 'Ordem de Serviço (OS)'), ('mapa_cotacao', 'Mapa de Cotação')], help_text='Tipo de solicitação (contrato, validação de contrato, medição, OS, mapa de cotação).', max_length=20, verbose_name='Tipo de Solicitação'),
        ),
    ]
