# Generated by Django 5.2.11 on 2026-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0025_add_tipo_validacao_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprovacaoemaildestinatario',
            name='obras',
            field=models.ManyToManyField(blank=True, help_text='Em branco: recebe cópia de pedidos aprovados de todas as obras. Se marcar obras, só recebe quando o pedido for de uma delas.', related_name='aprovacao_email_destinatarios', to='gestao_aprovacao.obra', verbose_name='Obras (filtro)'),
        ),
    ]
