# Generated by Django 5.2.12 on 2026-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0026_aprovacao_destinatario_obras'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='sigla',
            field=models.CharField(blank=True, help_text='3 letras maiúsculas que identificam a obra (ex: SRS)', max_length=3, null=True, unique=True, verbose_name='Sigla'),
        ),
    ]
