# Generated by Django 5.2.11 on 2026-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aprovacao', '0032_attachment_recusado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovacaoemaildestinatario',
            name='email',
            field=models.EmailField(help_text='Recebe cópia do e-mail de pedido aprovado (PDF consolidado com anexos e assinatura).', max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
