# Generated by Django 5.2.14 on 2026-06-12 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_merge_20260612_1544'),
        ('gestao_aprovacao', '0034_workorder_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='front',
            field=models.ForeignKey(blank=True, help_text='Frente da obra para este pedido. Deixe vazio para pedidos da obra inteira.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_gestao', to='core.projectfront', verbose_name='Frente'),
        ),
    ]
