# Generated by Django 4.2.11 on 2025-12-17 12:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
        ('suprimentos', '0003_insumo_categoria_insumo_data_atualizacao_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaorecebimento',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observação da alocação'),
        ),
        migrations.AlterField(
            model_name='alocacaorecebimento',
            name='item_mapa',
            field=models.ForeignKey(blank=True, help_text='Item do mapa que recebeu a alocação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes', to='suprimentos.itemmapa'),
        ),
        migrations.AlterField(
            model_name='alocacaorecebimento',
            name='local_aplicacao',
            field=models.ForeignKey(help_text='Local para onde foi alocado', on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='obras.localobra'),
        ),
        migrations.AlterField(
            model_name='alocacaorecebimento',
            name='quantidade_alocada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantidade alocada para este local', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='alocacaorecebimento',
            name='referencia_nf',
            field=models.ForeignKey(blank=True, help_text='NF específica (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='suprimentos.notafiscalentrada'),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='empresa_fornecedora',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='local_aplicacao',
            field=models.ForeignKey(blank=True, help_text='LOCAL onde será aplicado (Bloco A, Lobby, etc)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_mapa', to='obras.localobra'),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='nao_aplica',
            field=models.BooleanField(default=False, help_text='Marcar quando o item não se aplica'),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='numero_pc',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='numero_sc',
            field=models.CharField(blank=True, db_index=True, help_text='Nº SOLICITAÇÃO - Liga este item ao RecebimentoObra', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='prazo_necessidade',
            field=models.DateField(blank=True, help_text='Prazo que precisa do insumo', null=True),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='prazo_recebimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='quantidade_planejada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantidade NECESSÁRIA neste local', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='quantidade_recebida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='LEGADO: Total recebido na obra (usar RecebimentoObra)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='itemmapa',
            name='status_sienge_raw',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='RecebimentoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sc', models.CharField(db_index=True, help_text='Nº SOLICITAÇÃO (chave de ligação)', max_length=100)),
                ('data_sc', models.DateField(blank=True, null=True)),
                ('numero_pc', models.CharField(blank=True, db_index=True, help_text='Nº PEDIDO DE COMPRA', max_length=100)),
                ('data_pc', models.DateField(blank=True, null=True)),
                ('empresa_fornecedora', models.CharField(blank=True, help_text='Fornecedor', max_length=200)),
                ('prazo_recebimento', models.DateField(blank=True, help_text='Prazo previsto de entrega', null=True)),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantidade solicitada no pedido', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantidade que CHEGOU NA OBRA (sem especificar local)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('saldo_a_entregar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo pendente de entrega', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('numero_nf', models.CharField(blank=True, help_text='Nº da última NF', max_length=100)),
                ('data_nf', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='suprimentos.insumo')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Recebimento na Obra',
                'verbose_name_plural': 'Recebimentos na Obra',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='alocacaorecebimento',
            name='recebimento',
            field=models.ForeignKey(blank=True, help_text='Recebimento de onde veio o material', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='suprimentos.recebimentoobra'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='recebimento',
            field=models.ForeignKey(blank=True, help_text='Recebimento vinculado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='suprimentos.recebimentoobra'),
        ),
        migrations.AddIndex(
            model_name='recebimentoobra',
            index=models.Index(fields=['obra', 'insumo'], name='suprimentos_obra_id_ca3eca_idx'),
        ),
        migrations.AddIndex(
            model_name='recebimentoobra',
            index=models.Index(fields=['numero_sc'], name='suprimentos_numero__7bf4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='recebimentoobra',
            index=models.Index(fields=['numero_pc'], name='suprimentos_numero__36f7ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recebimentoobra',
            unique_together={('obra', 'numero_sc')},
        ),
    ]
