# Generated by Django 4.2.11 on 2025-12-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
        ('suprimentos', '0006_add_categoria_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recebimentoobra',
            unique_together={('obra', 'numero_sc', 'insumo')},
        ),
        migrations.AddIndex(
            model_name='recebimentoobra',
            index=models.Index(fields=['obra', 'numero_sc'], name='suprimentos_obra_id_d3b9ea_idx'),
        ),
    ]
