# Generated by Django 4.2.11 on 2025-12-17 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suprimentos', '0007_multiplos_insumos_por_sc'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('ALOCACAO', 'Alocação'), ('STATUS', 'Mudança de Status'), ('IMPORTACAO', 'Importação Sienge')], max_length=20)),
                ('campo_alterado', models.CharField(blank=True, help_text='Campo que foi alterado', max_length=100)),
                ('valor_anterior', models.TextField(blank=True, help_text='Valor antes da alteração')),
                ('valor_novo', models.TextField(blank=True, help_text='Valor após a alteração')),
                ('descricao', models.TextField(help_text='Descrição legível da alteração')),
                ('insumo_nome', models.CharField(blank=True, help_text='Nome do insumo (para exibição)', max_length=200)),
                ('local_nome', models.CharField(blank=True, help_text='Nome do local (para exibição)', max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('item_mapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='suprimentos.itemmapa')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to='obras.obra')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Alteração',
                'verbose_name_plural': 'Histórico de Alterações',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['obra', '-data_hora'], name='suprimentos_obra_id_fbdf94_idx'), models.Index(fields=['item_mapa', '-data_hora'], name='suprimentos_item_ma_2707b3_idx'), models.Index(fields=['usuario', '-data_hora'], name='suprimentos_usuario_a7a706_idx')],
            },
        ),
    ]
