# Generated by Django 4.2.11 on 2025-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
        ('suprimentos', '0010_alter_historicoalteracao_tipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recebimentoobra',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemmapa',
            name='item_sc',
            field=models.CharField(blank=True, db_index=True, help_text='Nº do ITEM na SC (quando houver). Ajuda a linkar a linha correta do Sienge.', max_length=50),
        ),
        migrations.AddField(
            model_name='recebimentoobra',
            name='descricao_item',
            field=models.CharField(blank=True, help_text='Descrição da linha no mapa do Sienge (pode diferir do cadastro do insumo).', max_length=500),
        ),
        migrations.AddField(
            model_name='recebimentoobra',
            name='item_sc',
            field=models.CharField(blank=True, db_index=True, help_text='Nº do ITEM na SC (linha do mapa exportado). Ajuda a diferenciar múltiplas linhas na mesma SC.', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='recebimentoobra',
            unique_together={('obra', 'numero_sc', 'insumo', 'item_sc')},
        ),
    ]
