# Generated by Django 4.2.11 on 2026-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0012_add_eh_macroelemento_to_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidade',
            field=models.CharField(blank=True, default='', help_text='Unidade de medida (KG, M², UND, etc) - preencher manualmente', max_length=20),
        ),
    ]
