# Generated by Django 4.2.11 on 2025-12-16 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sienge', models.CharField(db_index=True, help_text='Código único da obra no Sienge', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('nome', models.CharField(max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BLOCO', 'Bloco'), ('PAVIMENTO', 'Pavimento'), ('APTO', 'Apartamento'), ('SETOR', 'Setor'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='mapa_obras.obra')),
                ('parent', models.ForeignKey(blank=True, help_text='Local pai (ex: Bloco A -> Pavimento 1)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mapa_obras.localobra')),
            ],
            options={
                'verbose_name': 'Local da Obra',
                'verbose_name_plural': 'Locais da Obra',
                'ordering': ['obra', 'tipo', 'nome'],
                'unique_together': {('obra', 'nome', 'parent')},
            },
        ),
    ]
