# Generated by Django 4.2.11 on 2025-12-16 13:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapa_obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sienge', models.CharField(db_index=True, help_text='Código único do insumo no Sienge', max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=500)),
                ('unidade', models.CharField(default='UND', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='ItemMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_index=True, help_text='Ex: FUNDAÇÃO, ESTRUTURA, etc', max_length=100)),
                ('prioridade', models.CharField(choices=[('URGENTE', 'Urgente'), ('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], default='MEDIA', max_length=20)),
                ('nao_aplica', models.BooleanField(default=False, help_text='Marcar quando o item não se aplica (apenas CHEFIA pode marcar)')),
                ('descricao_override', models.CharField(blank=True, help_text='Descrição alternativa sem quebrar vínculo com insumo', max_length=500)),
                ('responsavel', models.CharField(blank=True, help_text='Responsável técnico', max_length=200)),
                ('prazo_necessidade', models.DateField(blank=True, help_text='PRAZO', null=True)),
                ('quantidade_planejada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacao_eng', models.TextField(blank=True)),
                ('numero_sc', models.CharField(blank=True, db_index=True, help_text='Nº SOLICITAÇÃO', max_length=100)),
                ('data_sc', models.DateField(blank=True, null=True)),
                ('numero_pc', models.CharField(blank=True, db_index=True, help_text='Nº PEDIDO DE COMPRA', max_length=100)),
                ('data_pc', models.DateField(blank=True, null=True)),
                ('empresa_fornecedora', models.CharField(blank=True, help_text='EMPRESA RESPONSÁVEL (fornecedor)', max_length=200)),
                ('prazo_recebimento', models.DateField(blank=True, help_text='PRAZO RECEBIMENTO (previsto)', null=True)),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('saldo_a_entregar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status_sienge_raw', models.CharField(blank=True, help_text='Texto do ERP, se vier', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_mapa_criados', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_mapa', to='suprimentos.insumo')),
                ('local_aplicacao', models.ForeignKey(blank=True, help_text='Local onde será aplicado (rateio/setor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_mapa', to='mapa_obras.localobra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_mapa', to='mapa_obras.obra')),
            ],
            options={
                'verbose_name': 'Item do Mapa',
                'verbose_name_plural': 'Itens do Mapa',
                'ordering': ['obra', 'categoria', 'insumo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEventoSuprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIADO', 'Item Criado'), ('ATUALIZADO', 'Item Atualizado'), ('SC_CRIADA', 'Solicitação Criada'), ('PC_CRIADA', 'Pedido Criado'), ('NF_RECEBIDA', 'NF Recebida'), ('ALOCADO', 'Alocação Realizada'), ('COMENTARIO', 'Comentário')], max_length=50)),
                ('mensagem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='suprimentos.insumo')),
                ('item_mapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='suprimentos.itemmapa')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='mapa_obras.obra')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Evento',
                'verbose_name_plural': 'Registros de Eventos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pc', models.CharField(blank=True, db_index=True, max_length=100)),
                ('numero_nf', models.CharField(db_index=True, max_length=100)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='suprimentos.insumo')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='mapa_obras.obra')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Entrada',
                'verbose_name_plural': 'Notas Fiscais de Entrada',
                'ordering': ['-data_entrada', '-created_at'],
                'unique_together': {('obra', 'insumo', 'numero_nf', 'data_entrada', 'numero_pc')},
            },
        ),
        migrations.CreateModel(
            name='AlocacaoRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_alocada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_alocacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='suprimentos.insumo')),
                ('item_mapa', models.ForeignKey(blank=True, help_text='Item planejado, se quiser ratear por linha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes', to='suprimentos.itemmapa')),
                ('local_aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='mapa_obras.localobra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='mapa_obras.obra')),
                ('referencia_nf', models.ForeignKey(blank=True, help_text='NF específica, se quiser ratear por NF', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='suprimentos.notafiscalentrada')),
            ],
            options={
                'verbose_name': 'Alocação de Recebimento',
                'verbose_name_plural': 'Alocações de Recebimento',
                'ordering': ['-data_alocacao'],
            },
        ),
        migrations.AddIndex(
            model_name='itemmapa',
            index=models.Index(fields=['obra', 'categoria'], name='suprimentos_obra_id_ea051c_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmapa',
            index=models.Index(fields=['obra', 'insumo'], name='suprimentos_obra_id_c7a8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmapa',
            index=models.Index(fields=['numero_sc'], name='suprimentos_numero__772f07_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmapa',
            index=models.Index(fields=['numero_pc'], name='suprimentos_numero__800b47_idx'),
        ),
    ]
